pods-framework/pods

classes/Pods.php

In PR #2350 I attempted to fix bug #2277, and it did but also removed the sorting by the weight.
This should fix #2567 as well as not regressing the fix for #2277

Allow fields to be sorted by weight or by orderby

---

classes/fields/color.php
includes/data.php
init.php

Fix pods_version_check usage

---

README.md
init.php

set version to 2.5.1 alpha in 2.x branch 

---

init.php

fix version constant in master

---

classes/PodsAPI.php

Fixing issue with delete_field() - updates #2593

---

readme.txt

Update plugin integration list

---

components/Templates/includes/functions-view_template.php

field() will return '' on an empty or non-existant field
Fixes #2626

Make sure if shortcode works properly

---

languages/pods-es_ES.po
languages/pods-fr_FR.po
languages/pods-it_IT.po
languages/pods-nl_NL.po
languages/pods-pt_BR.po
languages/pods-ro_RO.po
languages/pods-ru_RU.po
languages/pods-sk_SK.po
languages/pods-zh_CN.po

Update translation strings for 2.5.1

---

classes/PodsAPI.php
classes/PodsData.php
tests/includes/testcase.php
tests/includes/tests-traversal.php

Bug that was introduced by the fix for #2398, this fixes both of the issues.
Fixes #2607

Allow custom tax tables to be joined properly

---

README.md
init.php
package.json

Updates version number to 2.5.1 in all places, except readme.txt, which is covered by #2604
#2603

Update version number to 2.5.1

---

readme.txt

DO NOT MERGE YET.
Blockers to merge:

Update readme for 2.5.1

---

README.md
init.php
package.json
readme.txt

Set version 2.5.1.1

---

classes/PodsInit.php

Move rewrite_rules flush to later in init

---

classes/Pods.php

Somewhat related to issue #2376

Make last_id return a value

---

classes/PodsInit.php
components/Templates/class-pods_templates.php

Ensure codemirror css JS is enqueued with templates

---

ui/admin/settings-tools.php

Add Caching info to Settings Page

---

ui/css/pods-ui-list-table.css

See https://github.com/pods-framework/pods/issues/2680

Redesigning components category filter bar

---

includes/data.php

Ensure returned URLs are sanitized

---

ui/fields/attachment.php
ui/fields/media.php

Add pods_media_attachment filter to mimic pods_upload_attachment filter during upload so you can override things like the link

---

README.md
init.php
package.json
readme.txt

Also update changleog and stable tag to reflect existence of 2.5.1.1
#2635

Set version 2.5.2-a-1. 

---

ui/css/codemirror.css

https://github.com/pods-framework/pods/issues/2288

Fixing issue: #2288

---

ui/fields/select2.php

Remove extra semicolon

---

classes/PodsAdmin.php

Don't print shortcode button if disabled

---

ui/admin/settings-reset.php

Reverts pods-framework/pods#2691

Revert "Missing _e()s and __() in ui/admin/settings-reset.php"

---

ui/css/pods-wizard.css

Making the button more better and simple by taking away gradients. Better matches the redesigned Pods Wizard.

Updating .button.button-primary in  ui/css/pods-wizard.css

---

classes/Pods/API.php
classes/Pods/Admin.php
classes/Pods/Form.php
components/Templates/Templates.php
includes/data.php
tests/includes/tests-pods-api.php

Update class names

---

classes/Pods.php

Move id() call to stop infinite loop

---

classes/Pods/UI.php

Don't call apply_filters from the current class

---

classes/Pods/Init.php

Set JavaScript dependencies correctly

---

.gitmodules
README.md
composer.json
init.php

resolves #2710 
MERGE BLOCK: no longer valid.

Use composer for including cmb2

---

classes/Pods/View.php

Add workaround to WordPress serialize bug

---

classes/Pods/Admin.php

I'm not sure if this is the right fix, but it works.
Fixes #2735

Allow new field group to be added

---

classes/Pods/Metadata.php

Remove the require_once for CMB2 in PodsMeta constructor

---

ui/css/pods-wizard.css

Recently opened Firefox and saw something not so great...

Removing gradients #pods-wizard-box #pods-wizard-actions .button.button-secondary

---

classes/Pods/Data.php
classes/Pods/Object/Pod.php
tests/includes/test-pods-field-text.php
tests/includes/testcase.php
tests/includes/tests-pods-data.php
tests/includes/tests-pods-field-boolean.php

Changes needed for 3.0 tests to work

---

ui/admin/help.php

There were a few missing translatable strings in the file, so I just went ahead and added the rest.

Adding more translatable string in ui/admin/help.php

---

classes/PodsAdmin.php

This function is found in PodsAdmin.php

Inline docs for parent_file()

---

classes/Pods.php
classes/fields/pick.php

Needs confirmation, but should fix #2755 and maybe even fix #2271

Fix related field display

---

classes/Pods/Admin.php

Related to issue:  https://github.com/pods-framework/pods/issues/2753

Adding theme version to debug info

---

includes/general.php

Fixes #2763 and resolves leftover from #2765

Require params only if form is set

---

classes/PodsAdmin.php

Don't let Pods overwrite admin menu items

---

.travis.yml

travis-ci with php 7 but allow failures

---

.travis.yml

Reverts pods-framework/pods#2774

Revert "travis-ci with php 7 but allow failures"

---

.travis.yml

this time validated using lint
#2774  #2781

travis-ci: add php nightly but allow failures

---

ui/admin/settings-reset.php

https://github.com/pods-framework/pods/issues/2778

Clarify what does and doesn't get deleted on reset

---

ui/admin/settings-reset.php

Fixing Issue: #2778 (Clarify what does and doesn't get deleted on reset)

---

classes/fields/pick.php

Allow Display Field to work with relationships on CPT

---

classes/PodsData.php

Make sure the fields array is properly built

---

init.php

Add Github updater plugin meta info

---

classes/Pods/Field/Website.php
classes/Pods/Metadata.php
classes/Pods/Widget/Field.php
components/Builder/modules/field/PodsBuilderModuleField.php
components/Builder/modules/form/PodsBuilderModuleForm.php
components/Builder/modules/list/PodsBuilderModuleList.php
components/Builder/modules/single/PodsBuilderModuleSingle.php
components/Migrate-CPTUI/Migrate-CPTUI.php
components/Pages.php
components/Roles/Roles.php
components/Templates/Templates.php
components/Templates/class-pods_templates.php
sql/upgrade/PodsUpgrade.php
ui/fields/website.php
ui/front/widgets.php

This is just me fixing a bunch of random docs stuff. Also, there could be more PRs like this, beware...

NikV's 3.0 docs revamp

---

tests/includes/tests-traversal.php

Fix pick format type in traversal tests

---

classes/PodsUI.php

Proper escaping of attributes in submit element of PodsUI::manage

---

readme.txt

update youtube link in readme.txt 

---

Gruntfile.js
grunt-workflow.md

Automate Release Process with Grunt

---

classes/Pods/Data.php

Fixes #2869 
3.0 sibling of #2870

Add Pod name to cache key

---

components/Pages.php

Re: https://github.com/pods-framework/pods/issues/2872

pods_var()? BEGONE!

---

classes/Pods/API.php

PR for 3.0. Issue: https://github.com/pods-framework/pods/issues/2878

Stop saving _pods_[field_name] serialized when saving single select pick field values (3.0)

---

includes/general.php

Please see this issue: https://github.com/pods-framework/pods/issues/2789#issuecomment-89366384

Adding dashicon in place of a tooltip.

---

.travis.yml
classes/PodsMeta.php
classes/PodsTermSplitting.php

Support for Term Splitting in WP 4.2

---

classes/Pods.php

Reverts pods-framework/pods#2780

Revert "Feature/2779 term link"

---

readme.txt

2.5.2 changelog

---

init.php
package.json

Set version 2.5.3-a-1 in 2.x

---

classes/PodsView.php

Fix for symlinkd pods in local dev environment

---

classes/Pods/View.php

Per discussion in #2945 and revert and patch of PRs #2947
I can confirm this works in my local env too.

better fix for #2945 per discussion

---

classes/PodsView.php

I guess I shouldn't reset the HEAD locally then fix. :facepunch:

revert prev bad fix

---

classes/Pods.php
includes/general.php

Remove @internal phpDoc for pods_query()

---

classes/Pods/Field/File.php

Fix for #2957 (3.0 branch)

---

classes/Pods/View.php

Fix for #2945 (3.0 branch)

---

ui/js/jquery.pods.js

ui/js/jquery.pods.js fixes for #2971

---

ui/admin/form.php

Fix for ACT editor not staying on current item after saving

---

composer.json

composer: phpunit 4.7

---

ui/admin/form.php

Fixes #2752 for the 3.0 branch

Fixes #2752 for the 3.0 branch

---

ui/admin/form.php

Fixes #2752 for the 2.x branch

Fixes #2752 for the 2.x branch

---

classes/Pods/UI.php

Fixes #2843 for the 3.0 branch

Fixes #2843 for the 3.0 branch

---

classes/PodsUI.php

Fixes #2843 for 2.x branch

---

includes/general.php

Fixes #2932 for the 3.0 branch (props @str)

Fixes #2932 for the 3.0 branch (props @str)

---

ui/fields/datetime.php
ui/fields/time.php

Fixes #2804 for the 2.x branch

Fixes #2804 for the 2.x branch

---

ui/fields/datetime.php
ui/fields/time.php

Fixes #2804 for the 3.0 branch

Fixes #2804 for the 3.0 branch

---

ui/admin/shortcode.php

Fixes #2961 for the 2.x branch
Does not appear to be in the 3.0 branch

Fixes #2961 for the 2.x branch

---

classes/PodsMeta.php

This will make sure that pod instance will hold modified field value and the modified value go into the cache instead of old one.

2.x Update post filed in pod instance before saving

---

tests/includes/tests-shortcodes.php

Shortcode tests for #2932

---

tests/includes/tests-shortcodes.php

Shortcode tests for #2932 (3.0 branch)

---

includes/general.php
tests/includes/tests-shortcodes.php

Fix for #2807 (3.0 branch)

---

classes/PodsUI.php

Fixes for #3015 Pods UI reordering (2.x branch)

---

classes/Pods/UI.php

Fixes for #3015 Pods UI reordering (3.x branch)

---

classes/Pods/Components.php
classes/Pods/Data.php
includes/data.php
ui/fields/_db.php
ui/fields/codemirror.php
ui/fields/color.php
ui/fields/date.php
ui/fields/datetime.php
ui/fields/media.php
ui/fields/plupload.php
ui/fields/select2.php
ui/fields/time.php

#Feature/3.0/3012 pods clean name

---

classes/PodsComponents.php
classes/PodsData.php
includes/data.php
ui/fields/_db.php
ui/fields/attachment.php
ui/fields/codemirror.php
ui/fields/color.php
ui/fields/date.php
ui/fields/datetime.php
ui/fields/farbtastic.php
ui/fields/media.php
ui/fields/plupload.php
ui/fields/select2.php
ui/fields/time.php

pods_clean_name cleanup for 2.x

---

classes/Pods/API.php
classes/Pods/Data.php
tests/includes/testcase.php
tests/includes/tests-traversal.php

Add query_field tests (meta_query syntax for where) for 3.0

---

bin/ide-before-launch.sh
classes/PodsAPI.php
classes/PodsData.php
tests/includes/testcase.php
tests/includes/tests-traversal.php

Add query_field tests (meta_query syntax for where)

---

classes/PodsMeta.php

Fix style escaping

---

classes/widgets/PodsWidgetField.php
classes/widgets/PodsWidgetForm.php
classes/widgets/PodsWidgetList.php
classes/widgets/PodsWidgetSingle.php
classes/widgets/PodsWidgetView.php

Get rid of PHP4 constructor in widgets

---

classes/Pods/Widget/Field.php
classes/Pods/Widget/Form.php
classes/Pods/Widget/List.php
classes/Pods/Widget/Single.php
classes/Pods/Widget/View.php

This is the 3.0 sibling of #3056
Fixes #3055

Eliminate PHP4-style constructor in 3.x #3055

---

classes/PodsData.php

This isn't ready to get merged yet. Really just for @sc0ttkclark feedback and for testing. Also needs unit tests and 3.0 patch.
#3041

Add support for autoCAST()ing meta_value orderby for date and numbers

---

classes/Pods/Data.php

Fixes #3041 in 3.x
Is 3.x sibling of PR #3043

Add support for autoCAST()ing meta_value orderby for date and number in 3.x

---

components/Pages.php

Feature/pods page export support (3.0)

---

.scrutinizer.yml

too many declarations
can be minized imo
just psr/wordpress testing, hhvm testing etc
https://github.com/scrutinizer-ci/scrutinizer/pull/66

Copy of EDDs scrutinizer #2917

---

components/Templates/includes/functions-view_template.php

#3018
Future selves will thank you.

Notes about the workaround for taxonomies (2.x)

---

components/Migrate-CPTUI/Migrate-CPTUI.php

Issue #3109: Support multiple possible option names for post types and taxonomies (2.x)

---

components/Migrate-CPTUI/Migrate-CPTUI.php

Issue #3109: Support multiple possible option names for post types and taxonomies (3.0)

---

components/Migrate-CPTUI/Migrate-CPTUI.php

Issue #3109: `isnull` typo -> `is_null` (3.0)

---

components/Migrate-CPTUI/Migrate-CPTUI.php

Issue #3109: `isnull` typo -> `is_null` (2.x)

---

ui/css/pods-form.css

fixes spacing issues related to the autocomplete field format.

Changed content property to fix spacing issues with autocomplete field (2.x)

---

components/Templates/Templates.php
components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php

2.x PR for #3105
Assigning to @sc0ttkclark for review 
Needs 3.0 patch post-said review

Merge auto template into Templates component 

---

readme.txt

Updated Change Log for 2.5.5 #3131

---

license.txt

license: sync with gpl v2

---

readme.txt

Updating date and adding License.txt changes

Updating Change Log for 2.5.5 #3131

---

readme.txt

Update Change Log for date to 9/16 #3131

---

README.md

Add the Dockunit badge to the readme.

Add Dockunit badge

---

CONTRIBUTING.md

Improve Contributing guidelines

---

.travis.yml

travis: allow php 7 to fail

---

.travis.yml

http://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/

travis: cache composer

---

phpunit.xml.dist

phpunit: support for clover-coverage

---

components/Templates/Templates.php
components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php

For #3164
#3125 was 2.x version of this PR

Merge Auto Template into 3.x

---

.scrutinizer.yml

Reverts pods-framework/pods#3170
There's no label for "Awkward"

Revert "scrutinizer: less is more"

---

classes/PodsAdmin.php

Inline hook docs in PodsAdmin class 

---

Dockunit.json

https://github.com/dockunit/docker-prebuilt/commit/724bf9cb918faf503b1fb826bcd2133c5ae04959

dockunit: replace php 7 rc 1 with rc 4

---

components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php

Add pods_auto_template_template_name filter to change auto template 

---

phpunit.xml.dist

phpunit: support for clover-coverage FN

---

.scrutinizer.yml

scrutinizer: dump composer

---

classes/PodsAPI.php

Use $polylang->model to get the current language (since Polylang v1.2) if available.

Update polylang compatibility

---

.travis.yml

please include after release on thursday

travis: do not allow php 7 to fail

---

classes/PodsAdmin.php
ui/css/pods-flexible-relationships.css

Added css/enqueue logic for styling the modal popup windows for flexible relationships.

Add styles for modal window content

---

.travis.yml
classes/PodsAdmin.php

#3246 - Always show tab, explaining why it can't do anything if it can't.

Improve REST API Tab

---

classes/PodsAPI.php

Fix save_term error that's thrown when not needing to update data (only updating meta)

---

classes/PodsMeta.php
includes/general.php
tests/includes/tests-traversal.php

Add support for taxonomy terms in get_object without supplying taxonomy

---

classes/PodsAdmin.php
classes/PodsInit.php
classes/PodsRESTFields.php

Replace `register_api_field()` with `register_rest_field()`

---

Dockunit.json

https://github.com/dockunit/docker-prebuilt/commit/28f60ea5ab9ef729c799207f6c72c464b61b1e3b

Dockunit: use PHP 7.0 final

---

.travis.yml

#3283: Disable xdebug on Travis

---

classes/PodsInit.php
ui/admin/setup-edit.php

Add additional label support for Post Type / Taxonomy register functions

---

classes/PodsData.php

#3294: Non-zero array keys here in PHP 7 cause odd behavior so just strip the keys

---

init.php
package.json
readme.txt

#3281: update version number on 2.x

---

ui/admin/upgrade/upgrade_2_0_0.php

2 lines above each other should be inline with eachother

do not use hashtag as name

---

ui/fields/media.php

#3083: Over-escaping strikes again (file upload, restrict file types with more than one mime type)

---

ui/css/jquery.pods.attach.css

polished the upload field UI #3341

CSS changes to file upload field

---

classes/widgets/PodsWidgetSingle.php
includes/general.php
ui/admin/widgets/single.php

Add use_current option for Widget single

---

components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php

'type', not 'object_type'

---

classes/PodsRESTHandlers.php

Taxonomy custom meta fields returning false from REST API #3365

---

ui/css/pods-font.css

Removed [data-icon]:before block

Correcting CSS for Dashicon for Pods #3404

---

classes/fields/currency.php
classes/fields/number.php

Fixes pods-framework/pods-gravity-forms#34

Fix Currency/Number validation

---

classes/Pods.php

Fixes https://github.com/pods-framework/pods-gravity-forms/issues/37

Support object fields when using Pods::field() with a specific $field and $option

---

ui/css/jquery.pods.attach.css

Tried to make it look similiar to the wordpress modal uploader stylings for consistency. Can close out #3380

Changes to UI for progress bar styling

---

readme.txt

Updating Change Log for 2.6.2

---

includes/data.php
ui/fields/_db.php

Fix forcing underscores when loading edit Pod form

---

classes/PodsInit.php
classes/PodsView.php

Salt and pepper the cache keys

---

classes/PodsAPI.php
classes/fields/pick.php

Sorry for the previous commit. This time in the right place.
Support for the new Polylang versions
Plus some improvements.
Relative: #3223 https://github.com/pods-framework/pods/pull/3490
Also, we need to take a look at: #1801

Support for the new Polylang versions

---

classes/PodsAPI.php
classes/fields/pick.php

Related: https://github.com/pods-framework/pods/pull/3491
Wrong request: https://github.com/pods-framework/pods/pull/3502

Typo PLL (Polylang)

---

classes/PodsMeta.php

Allow adjusting the groups via filter
Related to #3547 
This simple change allows someone to do field grouping on their own before the official code is added.

Add filter to PodsMeta->groups_get()

---

components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php

Fix extra setting showing up in auto templates settings 

---

components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php

Allow changing auto template filter

---

classes/PodsForm.php

Use form_counter in field name to be unique and prevent conflicts

---

classes/PodsAPI.php

This will keep the "Pod not found" message from being displayed. There might be more to this issue since nothing is actually being saved to the actual Pod.
Related to #3416

Pass $strict = false to load_pod

---

classes/PodsRESTHandlers.php

REST API cleanup for pick field handling in #3559

---

includes/data.php

Add Polylang support to pods_v post_id

---

classes/PodsInit.php
classes/PodsRESTFields.php
classes/PodsRESTHandlers.php

*If $object_type is of type media, change to attachment as thats the identifier in REST

*Add user, media, and comment support to REST API

---

classes/PodsRESTFields.php

Add REST API v2 compatibility

---

classes/PodsAPI.php

Exclude unique post fields from duplication

---

readme.txt

Preparation for change log 2.6.6

---

includes/data.php

Related: https://github.com/pods-framework/pods/pull/3599

Fix issue with pll_get_post returning false instead of null

---

classes/PodsForm.php

Add PODS_DIR to directories that are checked by field_loader()

---

tests/includes/testcase.php
tests/includes/tests-traversal.php

Fix broken tests

---

classes/PodsAPI.php
classes/fields/pick.php

https://github.com/pods-framework/pods/issues/3594

Allow post_status filter to be set for related post_type objects in the edit field UI

---

classes/fields/link.php
ui/css/pods-form.css
ui/fields/link.php
ui/js/pods-link-picker.js

New PR for #3597
Bringing over PR from #3624

Bugfixes and improvements for 2.7 link field

---

classes/PodsRESTHandlers.php

Refactor object type checking in PodsRESTHandlers::get_handler

---

classes/PodsAdmin.php

Same filter as with the admin_menu function for consistency.
See https://github.com/pods-framework/pods/issues/3663

Allow page title of setting pages to be filtered

---

includes/general.php
init.php

Related:
https://github.com/pods-framework/pods/issues/825
https://github.com/pods-framework/pods/issues/2803
https://github.com/pods-framework/pods/issues/3353

Fix for fatal error when Pods is activated for the whole network.

---

includes/general.php

Related PR https://github.com/pods-framework/pods/pull/3473

Check for PodsInit in general.php

---

includes/general.php

Reverts pods-framework/pods#3473
Accidental master branch merge

Revert "Fix for fatal error when Pods is activated for the whole network."

---

classes/PodsForm.php

Fixes https://github.com/pods-framework/pods/issues/3682
Also allows for i18n module to improve translation handling.

Allow field options to be filtered (UI)

---

classes/Pods.php

Pods field() does not properly handle user and media when the output type is pod/pods

---

README.md

Update URL for translation contributions

---

classes/PodsRESTHandlers.php

*Fix sc0ttkclark's fail

---

ui/css/pods-admin.css
ui/js/floatmenu.js

Change floatmenu.js to consider current window/document dimensions and floatmenu item position.
https://github.com/pods-framework/pods/issues/3721

Improvements floatmenu.js

---

classes/PodsAPI.php

Otherwise the meta won't be "fresh".

Update postmeta cache before get_post_meta calls when bypassing cache

---

ui/admin/settings-tools.php

Should have looked, this should have be based on 2.x not master.
#3864

Revert "Fix opcache names and add OPcache"

---

classes/PodsAPI.php

Store the old field name in meta

---

classes/PodsAdmin.php

Add action after successful AJAX in admin_ajax

---

classes/PodsAdmin.php

Fix error with PODS_LIGHT and components

---

ui/css/pods-front.css
ui/css/pods-ui-list-table.css

CSS fixes (remove old images + linter)

---

ui/css/pods-form.css

Improve CSS for code field (CodeMirror)

---

ui/fields/date.php
ui/fields/datetime.php

Set start of week day from general settings.

---

classes/fields/oembed.php
ui/fields/oembed.php

Title says it all.
Mostly JS/PHP linting stuff. One warning ($css_id not defined)

oEmbed field: Fix some notices for PHP and JS

---

classes/PodsAPI.php

Error exporting taxonomy relationship

---

classes/PodsAdmin.php

Fixes https://github.com/pods-framework/pods/issues/3569

Use taxonomy capabilities in custom locations for taxonomy edit pages

---

.travis.yml

should save a couple of seconds for every build
#3756

travis: cache apt

---

classes/PodsAPI.php

Polylang: Fix SQL for multilingual taxonomies.

---

.codeclimate.yml

Code Climate integration

---

ui/js/admin-importer.js

https://codeclimate.com/github/pods-framework/pods/ui/js/admin-importer.js

admin-importer == to ===

---

.scrutinizer.yml

checks for incorrect / missing docblock

scrutinizer: phpdoc check

---

classes/PodsAdmin.php

No max-length for default field value

---

classes/Pods.php
classes/PodsUI.php

Adds a bulk action "Export Pods" in the Pods management, so that Pods data can be exported
Recreated from #3602

Added bulk action "Export" for Pods (2.7)

---

ui/fields/currency.php

*Allow negative numbers

---

ui/fields/media.php
ui/fields/plupload.php

Fix plupload file field listings

---

README.md

https://codeclimate.com/github/pods-framework/pods

readme.md add code climate

---

.travis.yml
bin/install-wp-tests.sh
bin/vagrant-wp-tests.sh
tests/phpunit/README.md
tests/phpunit/includes/testcase.php

Stop unit test teardown from deleting all data

---

ui/fields/plupload.php

*Remove bad init call

---

classes/fields/file.php

WP Gallery display options for image fields

---

classes/PodsRESTHandlers.php

Taxonomy class in WordPress 4.7

---

classes/PodsAPI.php
classes/PodsAdmin.php

Make new Custom Taxonomies Hierarchical by default

---

classes/PodsMeta.php

Fix get_meta() $single usage to ensure it's always a boolean

---

classes/Pods.php

Proper reset local var cache in Pods::$row when using add_to/remove_from/save

---

ui/css/jquery.ui.timepicker.css
ui/css/meta-boxes.css
ui/css/pods-admin.css
ui/css/pods-advanced.css
ui/css/pods-font.css
ui/css/pods-form.css
ui/css/pods-front.css
ui/css/pods-manage.css
ui/css/pods-wizard.css

css markup

---

classes/PodsUI.php

Add pods_ui_get_find_params filter for PodsUI to extend default find()

---

classes/PodsAPI.php

Properly clear cache before running post-save actions in PodsAPI::save_pod_item

---

classes/PodsMeta.php
includes/general.php

Update save_post / save_user handling with better fallbacks when nonce not active

---

classes/PodsAPI.php
classes/PodsMeta.php
includes/general.php

PodsMeta now returns false instead of die/exception for the `*_*_metadata` filters.
Fixes #3930

Revamp pods_error to handle multiple modes, PodsMeta now returns false instead of die/exception

---

classes/PodsAdmin.php
classes/PodsUI.php
ui/admin/form.php

See https://github.com/pods-framework/pods/issues/3736 and https://github.com/pods-framework/pods/issues/3735

Redo ACT label handling

---

classes/Pods.php
classes/PodsMeta.php
tests/phpunit/includes/tests-pods-meta.php

Fix additional save_user/save_post handling problems and add Unit Tests

---

classes/fields/currency.php
classes/fields/number.php

Fix: Number/Currency format validation error with French formatting

---

.travis.yml
init.php

Require PHP 5.3+ for Pods to work (needed for Pods 2.7 mv fields JSON)

Require PHP 5.3+ and WP 4.0+

---

classes/fields/file.php

See #3957
I've also set the indentation to match surrounding code (spaces)

Fix undefined index notice with Gallery options in file field

---

ui/fields/currency.php

One more time... with feelin'.

Fix for #4012

---

components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php

Adds configuration setting to override and allow to run outside of loop.

Only run auto templates if inside the WordPress loop

---

classes/PodsAdmin.php

Correct the text for the menu location of permalinks

---

classes/fields/pick.php

Add access rights checks for add new / edit links for modal

---

Gruntfile.js

Explicitly call node for dfv build/test tasks

---

classes/fields/pick.php

Fixes #4051

---

classes/PodsI18n.php
ui/js/pods-dfv/_src/core/iframe-frame.js
ui/js/pods-dfv/_src/file-upload/file-upload.js
ui/js/pods-dfv/_src/file-upload/uploaders/media-modal.js
ui/js/pods-dfv/_src/file-upload/uploaders/plupload.js
ui/js/pods-dfv/_src/file-upload/views/file-upload-item.html
ui/js/pods-dfv/_src/pick/pick.js
ui/js/pods-dfv/_src/pick/views/add-new.html
ui/js/pods-dfv/_src/pick/views/list-item.html
ui/js/pods-dfv/pods-dfv.min.js
ui/js/pods-i18n.js

Issue: #4056 
I18n in other PR's
- New string in #4032: 'Select from existing' - commit: 3fa214f

Pods DFV i18n

---

tests/js/pods-dfv/file-upload/models/relationship-model.js

JS Unit Tests for relationship model

---

classes/PodsMeta.php

Hidden fields don't save Default Values

---

classes/PodsAPI.php

Fix duplicate_pod_item for WP objects

---

classes/PodsInit.php

Use register_taxonomy_for_object_type for post types that support post formats

---

classes/PodsData.php

Fix post_author traversal for related posts

---

components/Roles/ui/edit.php
ui/css/pods-admin.css
ui/css/pods-ui-list-table.css
ui/css/pods-wizard.css

Follow up PR for CSS fixes.
Prev PR: #3968
Issue: #3967

CSS tweaks, fixes, and additions for 2.7 - Part 2

---

classes/PodsForm.php
classes/PodsMeta.php
ui/admin/components-admin.php
ui/admin/field-option.php
ui/admin/form-settings.php
ui/css/pods-admin.css
ui/js/jquery.pods.js

Support `wildcard-on` for field dependencies

---

classes/fields/pick.php
tests/js/pods-dfv/_setup.js
tests/js/pods-dfv/pick/pick-spec.js
ui/js/pods-dfv/_src/pick/pick.js
ui/js/pods-dfv/pods-dfv.min.js

Option to disable "Add New" for pick fields

---

components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php
components/Templates/includes/functions-pod_reference.php
includes/general.php

Feature/4087 merge templates improvments into 2.x

---

readme.txt

Streamlining to 12 Tags #3979

---

classes/Pods.php
classes/PodsAPI.php
classes/PodsData.php
classes/PodsForm.php
classes/fields/comment.php

Now we can traverse post comments in field and find (only supported by Post types)

Add support for Comment traversal in field and find

---

classes/PodsAPI.php
classes/fields/pick.php

ACT saving broken by #4108

---

classes/fields/pick.php

Modal Add/Edit for ACTs

---

classes/fields/pick.php
ui/js/jquery.pods.js

Handle modal add/edit for ACT ajaxed requests

---

classes/fields/pick.php

Auto template: saved settings not initializing correctly on load

---

.jshintrc

`esnext` is deprecated

---

classes/PodsField.php
classes/fields/pick.php

Disable add/edit when already in a pods modal or not in the admin

---

components/Templates/includes/functions-pod_reference.php

Correct usage of single and double quotes

---

ui/css/pods-dfv-list.css
ui/css/pods-form.css

Added lines between pod fields. Fixed scrollable View lists borders.

CSS: Metabox Form field borders + DFV list form field css changes

---

classes/PodsInit.php

Fix TEC conflict with Handlebars

---

ui/css/pods-dfv-list.css

List View - Needs Help Text on Edit, Link and Delete icons (and hover)

---

classes/PodsComponents.php
includes/general.php

Add back link to wp_die() usage

---

classes/PodsComponents.php
classes/PodsInit.php
classes/PodsUI.php
sql/upgrade/PodsUpgrade.php

Merge auto activate components fixes

---

classes/PodsAPI.php

Always return $id for AJAX requests.

---

ui/admin/setup-edit-field-fluid.php

This is just a text change for the Add Field button in #4175

Changed ‘Add Field’ to ‘Save Field’ as per #4175

---

classes/PodsAdmin.php
classes/fields/number.php

Fixes #2839
Also enhances the number field to optionally remove trailing decimals (zero's)

Allow float values for menu positions + option to remove trailing decimals from number field

---

classes/PodsAPI.php

Give preference to existing field option values (fixes #4003)

---

.babelrc
package.json
tests/js/pods-dfv/file-upload/models/file-upload-model.js
tests/js/pods-dfv/file-upload/models/relationship-model.js
tests/js/pods-dfv/pick/pick-spec.js
tests/js/pods-dfv/pick/views/select-view.js
ui/js/pods-dfv/_src/core/pods-field-views.js
ui/js/pods-dfv/_src/field-manifest.js
ui/js/pods-dfv/_src/file-upload/file-upload.js
ui/js/pods-dfv/_src/file-upload/uploaders/media-modal.js
ui/js/pods-dfv/_src/file-upload/uploaders/plupload.js
ui/js/pods-dfv/_src/file-upload/views/file-upload-form.js
ui/js/pods-dfv/_src/file-upload/views/file-upload-list.js
ui/js/pods-dfv/_src/file-upload/views/file-upload-queue.js
ui/js/pods-dfv/_src/model-manifest.js
ui/js/pods-dfv/_src/pick/pick.js
ui/js/pods-dfv/_src/pick/views/add-new.js
ui/js/pods-dfv/_src/pick/views/checkbox-view.js
ui/js/pods-dfv/_src/pick/views/list-view.js
ui/js/pods-dfv/_src/pick/views/radio-view.js
ui/js/pods-dfv/_src/pick/views/select-view.js
ui/js/pods-dfv/_src/pods-dfv-init.js
ui/js/pods-dfv/_src/pods-dfv.js
ui/js/pods-dfv/_src/rollup.config.dev.js
ui/js/pods-dfv/_src/rollup.config.prod.js

Switch from `babel-root-import` to `babel-plugin-module-resolver`

---

classes/fields/website.php

Add option to allow port in URLs for Website field

---

classes/PodsI18n.php
ui/css/pods-admin.css
ui/js/jquery.pods.js

Enhance Pods admin fields JS & CSS

---

classes/PodsAPI.php
classes/PodsMeta.php
components/Helpers.php
components/I18n/I18n.php
components/Pages.php
components/Templates/Templates.php
includes/general.php

Track more field changes (with support for tracking wp object field changes)

---

classes/Pods.php
classes/PodsAPI.php
classes/PodsRESTHandlers.php

Follow REST API meta key visibility for exported objects

---

classes/PodsAPI.php

This reverts commit 3c16e31caa5a2d2c621b9d36ca0cd1da712b57b2.

Revert "Give preference to existing field option values (fixes #4003)"

---

ui/js/jquery.pods.js

Migrate Package broken in 2.7

---

classes/PodsField.php
classes/fields/boolean.php
classes/fields/datetime.php
classes/fields/number.php
components/Templates/includes/functions-view_template.php

Issue: #4227 
- implement method in all fields accordingly

is_empty() field method + fix [if] template tags

---

ui/css/pods-dfv-list.css

Select2 search input responsive

---

classes/fields/pick.php

Modal add/edit requires media templates to be enqueued

---

classes/PodsAPI.php

Needs testing to confirm it fixes the issue, also testing to confirm relationships save and bidirectional saving works.
Fixes #4112

Possible fix for #4112

---

ui/admin/setup-add.php

'Indentifier' updated with 'Identifier'

spelling error ui/admin/setup-add.php Lines 186 and 197

---

readme.txt

Starting ChangeLog for 2.6.9

---

classes/PodsForm.php

Disable link field for now

---

classes/PodsForm.php
classes/fields/link.php

Fixes display issue with link field

Link field: Add display_list functionality for display

---

ui/admin/help.php

Use 2.x branch for github feed

---

includes/general.php

Fix for issues when Pods shortcodes are embedded in HTML

---

components/Pages.php
components/Templates/Templates.php

Related: #4311 
Will also include them in Pods role manager

Add pods_template caps to the members caps filter

---

readme.txt

Updating ReadMe.txt for 2.6.10

---

init.php

Added some comments to improve our trail here for ourselves as we run releases.
Upped minimums:
* WP 4.5+
* PHP 5.3+
* MySQL 5.5+

Update info for minimum versions

---

readme.txt

It was incompatible with WP.org

Typo in README

---

readme.txt

Minor markup fix for 2.6.10 version changelog

Changelog markup fix

---

.travis.yml

TravisCI failing on PHP 5.3

---

ui/admin/setup-edit.php

Fix do_meta_boxes call to use the proper $pod_post

---

classes/PodsMeta.php

In Pods, Pods recurse YOU in Pods, Pods recurse YOU in Pods
Fixes #4385 Fixes #4385 Fixes #4385 Fixes #4385 Fixes #4385

Stop adding groups forever when adding to multiple pods forever when adding to multiple pods forever when adding multiple pods forever

---

classes/Pods.php
classes/fields/pick.php

Simple predefined lists passing value as a string

---

classes/PodsMeta.php

Don't interfere with getting locale from user meta

---

components/Roles/Roles.php

`WP_User_Search` is deprecated

---

classes/PodsForm.php
ui/js/jquery.pods.js

Fixes #4038 
This is a two-parter:

Fixes for showing/hiding some of the List View specific options

---

classes/fields/pick.php

Users might want certain modals to work on frontend or nested
Resolves #4426

Pass DFV config and args to filters

---

classes/PodsData.php

Also adds documentation for two filters
Resolves #4428

Pass PodsData object to pods_data_pre_select_params filter

---

classes/fields/pick.php

Add CA Provinces to pre-defined lists for Relationship field type

---

classes/PodsData.php

Add 'pods_get_sql' filter

---

README.md

prefer https for domain pods.io

minor readme link improvement

---

classes/PodsData.php

Fix where_default logic more

---

ui/front/form.php

Make sure all required array keys exist.

---

classes/fields/currency.php
classes/fields/number.php
tests/phpunit/includes/tests-traversal.php

Fix number and currency prepare for WP 4.8.2 backcompat breakage

---

classes/PodsAPI.php

Fix php notice with get_posts() call

---

classes/fields/file.php

Plupload file size limits specified in KB are miscalculated as MB

---

classes/PodsRESTHandlers.php

Add hook for output type in REST responses for relationship fields

---

ui/js/jquery.pods.js

Roles AJAX data

---

classes/fields/file.php

Tooltip with valid size suffixes and default info

---

classes/PodsMeta.php
tests/phpunit/includes/Templates/Test_Frontier.php

Creating test under directory, presumably more template tests will go there
This should fail initial tests, after tests I'll add a commit to fix the issue.
Fixes #4500

Add test for saving template

---

classes/PodsI18n.php

Add Pods templates to i18n enabled post-types for Polylang

---

classes/fields/pick.php

Use the correct field index, `post_title` is only gonna work for posts

---

classes/fields/file.php

Ensure the media library is initialized wherever we have file upload fields

---

tests/phpunit/includes/Bugs/Test_4097.php

I accidentally left this one in there, sorry!
Does not cause any problems
Resolves #4537

Remove var_dump from test

---

.travis.yml
bin/init.sh

Force node v7 for precise/PHP 5.3 tests

---

ui/front/form.php

Make sure the document is ready before initializing Pods().

---

classes/PodsMeta.php

Fixes: #4101 
AC mentions: @tobiasschutter @DGStefan

Compatibility with Admin Columns v3.0+

---

classes/PodsAPI.php

Fix `is_new_item` param for `duplicate()`

---

init.php

Update GitHub updater branch

---

ui/admin/setup-add.php

Update ignored post types / taxonomies, fix link manager handling

---

readme.txt

Provides Read Me Update/Change Log for #4455

Updating readme.txt for 2.7 Release

---

package.json

Fix devDependencies

---

classes/PodsAPI.php

Add join table logic for taxonomy

---

readme.txt

Fixing link to Developer Notes for 2.7

---

readme.txt

Update changelog for 2.7.1

---

classes/Pods.php
classes/PodsAPI.php
classes/PodsInit.php
classes/PodsMigrate.php
classes/PodsUI.php
classes/cli/PodsAPI_CLI_Command.php
classes/cli/Pods_CLI_Command.php
init.php
readme.txt

Add WP-CLI commands

---

.travis.yml

Skip npm install and js tests on the PHP 5.3/Precise box

---

ui/fields/number.php

Simplify how we inject the PHP string into the JS

---

classes/fields/text.php

Text field readonly fix

---

classes/fields/number.php

Fixes #4741 , not sure if there are unintended consequences though it seems fairly harmless.

Fixed printing numbers having more than 6 decimals with sprintf. #4741

---

readme.txt
ui/front/form.php
ui/front/view.php

Not sure if the filter name 'pods-field-html-class' follows any standards, feel free to change.

Added HTML class filters for feature/4813-form-html-classes

---

includes/general.php

Qtip init was registered but not enqueued in certain cases

---

classes/Pods.php

Allow traversing into post_thumbnail

---

classes/PodsAPI.php

Extend the condition for WPML validation exception to cover the TE

---

classes/fields/datetime.php
ui/fields/date.php
ui/fields/datetime.php
ui/fields/time.php

Adjust method handling for datetime/time/date format needs

---

readme.txt

Update Readme.txt for 2.7.2 Release

---

classes/widgets/PodsWidgetField.php
classes/widgets/PodsWidgetForm.php
classes/widgets/PodsWidgetList.php
classes/widgets/PodsWidgetSingle.php
classes/widgets/PodsWidgetView.php

Formerly `extract`ed variables were in `$args`, not `$instance`

---

ui/fields/slider.php

Add 'pods-compat-container' class for jquery-ui sliders

---

classes/fields/datetime.php

Try/catch exception for DateTime

---

ui/front/form.php

Fix filter pods_form_html_class

---

readme.txt

Prep changelog PR for 2.7.2.1

---

classes/fields/color.php

Check if $color has a value before checking this value.

---

classes/fields/pick.php

Multiselect predefined lists not finding the proper selected IDs

---

docs/issue_template.md
docs/pull_request_template.md

Fix #4924 for Issue Template
Fix: Updating Issue Templates for better workflow #4924 @jimtrue

Updating Issue Template to fix #4924

---

classes/PodsInit.php

`get_current_screen()` may not always be defined, even if `is_admin()` is true

---

classes/PodsInit.php

Always enqueue DFV on any post type edit

---

classes/PodsAdmin.php

Add tooltip for the `Hierarchical` option for taxonomies

---

classes/PodsMigrate.php
readme.txt

Fix false check for file uploads directory check when exporting

---

includes/general.php

Bypass `session_start()` if a valid user is logged in

---

.gitignore
bin/phpcs-audit.sh
bin/phpcs-autofix.sh
phpcs.xml.dist

PHP Codesniffer audit script

---

classes/fields/pick.php

Refactor logic for determining whether or not to activate AJAX mode for autocomplete based field views

---

readme.txt

Changelog for 2.7.4

---

readme.txt

Changelog for 2.7.5

---

classes/fields/pick.php

Records added modally via DFV's 'Add New' were not being selected

---

readme.txt

Changelog for 2.7.6

---

components/Roles/ui/edit.php

Non-internationalized string "Add Another Custom Capability"

---

classes/fields/time.php

Override the `is_empty()` method on the time field

---

classes/PodsAPI.php
classes/PodsMigrate.php
classes/PodsUI.php
classes/PodsView.php
components/Roles/ui/edit.php
sql/update-2.0-beta.php
ui/admin/form.php
ui/admin/shortcode.php
ui/admin/view.php
ui/fields/attachment.php
ui/fields/slider.php
ui/front/form.php

Fix violations from the `WordPress.WhiteSpace.PrecisionAlignment` sniff.
Fixes #5026
Before: 
After:
Code standards.

PHPCS: Fix WordPress.WhiteSpace.PrecisionAlignment

---

classes/PodsUI.php

Fix "Export all" button for ACTs

---

readme.txt

Changelog for 2.7.7

---

includes/general.php

* Added pods_shortcode_output filter to allow customization of shortcode output based on shortcode attributes

Add pods_shortcode_output filter

---

readme.txt

Changelog for 2.7.9

---

README.md
classes/Pods.php
classes/PodsI18n.php
includes/general.php
init.php
package.json
readme.txt

Pods 2.7.9

---

rollup.config.js

Encapsulate React and ReactDOM.

---

classes/fields/file.php

Allow Media Library on forms in front facing pages

---

ui/admin/setup-edit-field.php
ui/js/jquery.pods.js

#5200 
- Add bi-directional status label to relationship fields.

Relationship field - bidirectional label

---

README.md

Use branch relative linking for md file in readme

---

ui/front/form.php
ui/js/jquery.pods.js

Fixes: #5136
Enhances dependencies on load + make simple select fields from DFV pick field compatible.
I also added an event listener for when jQuery is loaded in the footer to prevent jQuery errors.
See #5137

Frontend forms conditional logic v2

---

classes/PodsComponents.php

Fixes #5221
N/A, introduced as regression only in this release

Fix component header parsing for developer/tableless mode

---

readme.txt

Changelog for 2.7.10

---

readme.txt

2.7.11 changelog

---

classes/PodsInit.php

Fixes the updatedrrrr string
* Fixed: Resolved typo in "updated" text

updatedrrrr means updated but with 4 extra Rs

---

readme.txt

Changelog for #5247

---

classes/fields/pick.php

Do not force pick item IDs to zero

---

classes/fields/website.php

Force WWW options have never worked

---

classes/PodsAPI.php

Avoid redundant transient set

---

classes/fields/pick.php

Fixes #5299
`Support meta fields that aren't pod fields as display field for relationships`

Support meta fields as display field for relationships

---

classes/Pods.php
classes/PodsData.php

Undefinied var names being passed to compact

---

classes/PodsAdmin.php
classes/PodsInit.php

Needed to create a way for users to enable DFV on the front end of websites for those of us who use tools like Beaver Builder to extend post types.

Create filter for enqueueing dfv on frontend

---

rollup.config.js

Rollup config: set `browser: true` for node-resolve

---

ui/js/pods-dfv/_src/core/react/pods-dfv-validation-message.js

Components for validation messages

---

ui/admin/setup-edit.php

Sister field fix after changes to the PodsDFV.fields object

---

composer.json

WP Coding Standards
bump from 0.14 to 1.1, released last week
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/1.1.0 
- [ x] My code is tested.
- [x ] My code follows the WordPress code style.
- [x ] My code follows has proper inline documentation.

Composer: WP Coding Standards 1.1

---

classes/PodsAPI.php

Fixed: #5276
Checked table configuration after adding a new ACT + verified adding emoji in the title works (See #5276 )
- Set table charset for Pods Advanced Content Types to WP default charset. #5276

Fix ACT table charset

---

classes/fields/currency.php

Additional Currency for use in PODs - the Nigerian Naira

Added Nigerian Naira to PODs

---

classes/Pods.php

Fixes #5436 
Use `is_callable` instead of `function_exists`.
* Allow all callables to be passed in magic tags.

Allow all callables in helpers

---

classes/fields/currency.php

Fixes #5446 
* Fixed: Corrected Malaysian Ringgit currency sign

Correct Malaysian Ringgit currency sign

---

ui/fields/datetime.php

Fixes: #5460 (verified by issue author)
* Fixed: datetime-local HTML5 input format

Fix datetime-local HTML5 input format

---

components/Migrate-Packages/Migrate-Packages.php
tests/phpunit/includes/Bugs/Test_5476.php

Fixes #5476
First commit adds test, after watching travis fail on this I'll commit the actual fix
Fix: Allow migrate packages to import pages #5476 (@jamesgol)

Allow migrate packages import to work with reserved words

---

.github/workflows/mt-code-review.yml
classes/PodsUI.php

Fixes #5503
Closes #5176 
As stated in the issues above the capabilities for ACT's do not work properly. This PR fixes the access checks for ACT's.
* Refactor and fix issues with Advanced Content Types capabilities.

Refactor capability checks for ACT's

---

classes/PodsAPI.php

Reverts pods-framework/pods#5511

Revert "Sanitize meta values before passing to *_post_meta functions"

---

.github/workflows/mt-code-review.yml
classes/PodsUI.php

Fixes #5509 
Previous:
PR:
* Fix & Enhance ACT list view pagination

Fix/Enhance ACT list view pagination

---

classes/PodsAPI.php

Allow Pods to ALTER table if the SQL field definition  has changed (not just name)

---

classes/PodsInit.php
ui/js/pods-dfv/_src/core/iframe-frame.js
ui/styles/src/base/_admin.scss
ui/styles/src/base/_form.scss
ui/styles/src/base/_ui-list-table.scss
ui/styles/src/libs/_jquery-qtip.scss

Fixes for WP 5.3

---

includes/general.php

As requested by @sc0ttkclark 
Enhancement for #5310

Validate query tags before default to current object

---

ui/admin/setup-edit-field-fluid.php
ui/js/jquery.pods.js

Fixes: #5311
Also refactores the `sluggable_single` method to make it more readable and jQuery more efficient.

Add sanitize_title option to sluggables instead of applying default

---

readme.txt

2.7.16 changelog

---

README.md
components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php
init.php
package.json
readme.txt

Revert 5289 feature/4768 pr work

---

components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php

Fix removed main filter for auto templates

---

classes/PodsAdmin.php

Just refactoring, no issue linked.
- None needed.

Enhance and cleanup code adding menu pages.

---

classes/fields/boolean.php

Allow No (0) as an answer for radio and select boolean fields

---

components/Advanced-Content-Types.php
components/Advanced-Relationships.php
components/Builder/Builder.php
components/Helpers.php
components/I18n/I18n.php
components/Markdown.php
components/Migrate-CPTUI/Migrate-CPTUI.php
components/Migrate-Packages/Migrate-Packages.php
components/Pages.php
components/Roles/Roles.php
components/Table-Storage.php
components/Templates/Templates.php

Only single line properties are allowed.
Fixes: #5543 
- Fixed: component descriptions.

Fix components meta to be compatible with get_file_data()

---

classes/PodsI18n.php

Fixes #5556 
- Fix PHP 7.4: Trying to access array offset on value of type bool

Validate $lang_data before accessing array

---

classes/PodsAPI.php

Add new actions to hook into when saving field and handling table ALTER queries.
Added: New hooks when saving field table definitions (table-based Pods).

Add new actions when saving field during table altering

---

classes/PodsAPI.php
classes/PodsData.php

Related: #5456 
This PR is to find and fix any PHP 7.4 related issues we can find.

Fix PHP 7.4 notices

---

readme.txt

2.7.17 changelog

---

includes/data.php
tests/phpunit/includes/tests-pods-data.php

Fix pods_trim charlist

---

components/Pages.php
components/Templates/Templates.php

- UI: Prefix Pages and Templates components with "Pod" in admin menu

Prefix Pages and Templates components with "Pod" in admin menu

---

classes/PodsAPI.php

Fix newer array notation

---

classes/fields/currency.php
classes/fields/number.php
tests/phpunit/includes/tests-pods-field-currency.php

Fixes: #5651 
Bug introduced in: #5439

Number/Currency: Fix parsing input in various formats

---

includes/data.php
tests/phpunit/includes/tests-pods-data.php

Use wp_list_filter() to remove duplicate code

---

classes/PodsAdmin.php

Fix taxonomy option rewrite with front label tooltip

---

classes/fields/wysiwyg.php
ui/fields/tinymce.php

Fixes: #3716
Fixes: #5671
- ~~My code includes PHP Unit Tests (if applicable)~~

WYSIWYG: Custom editor height

---

classes/PodsAdmin.php
classes/PodsInit.php
classes/PodsUI.php
classes/fields/date.php
classes/fields/datetime.php
classes/fields/file.php
classes/fields/link.php
classes/fields/time.php
classes/fields/website.php
components/Helpers.php
components/Pages.php
components/Roles/Roles.php
components/Templates/Templates.php
includes/general.php
ui/admin/form.php
ui/admin/help.php
ui/admin/setup-add.php
ui/admin/setup-edit.php
ui/admin/upgrade/backup.php
ui/admin/view.php
ui/admin/widgets/list.php
ui/admin/widgets/single.php
ui/js/pods-dfv/_src/file-upload/views/file-upload-item.html
ui/js/pods-dfv/_src/pick/views/list-item.html

Add noopener and noreferrer for all target _blank links

---

classes/PodsAPI.php

Applying PR merge from https://github.com/pods-framework/pods/pull/5706

Nested relationship fields should render as array of objects

---

classes/PodsMeta.php
tests/phpunit/includes/Meta/Metadata.php
tests/phpunit/includes/Meta/Test_Metadata.php

Fixes: #5660 (confirmed by user)
Fixes: #5685
Fixes: #5696

Simplify & fix parsing proper meta_value format

---

classes/Pods.php
includes/general.php

This PR isn't intented as a feature or enhancement.
Just refactoring code, making it more understandable and compact: reusing variables and removing duplicate code.

Various Pods::field() enhancements

---

classes/Pods.php

- ~~My code includes PHP Unit Tests (if applicable)~~

Pods::process_magic_tags() enhancements

---

readme.txt

TODO: Release date @sc0ttkclark

2.7.21 changelog

---

classes/PodsRESTHandlers.php

Fixes #5752 
- Fix REST fields for media Pod.
~- My code includes PHP Unit Tests (if applicable)~

Fix REST fields for media Pod

---

includes/general.php

Fixes: #5767 
https://wordpress.org/support/topic/templates-capablility_allowed-in-serialized-form/

pods_permission() > use maybe_unserialize()

---

classes/fields/file.php

Fix possible PHP warning in file.php

---

classes/PodsAPI.php
classes/fields/file.php
classes/fields/pick.php
includes/general.php
ui/admin/form-settings.php
ui/admin/form.php
ui/fields/attachment.php
ui/front/form.php

Implement session_status() & pods_session_id()

---

classes/PodsAdmin.php

Redirect to next Pod admin page if needed

---

ui/admin/setup-edit-field.php

Fixes: #5686 
@sc0ttkclark Please check filter name.

Fix empty filter: `pods_ignored_pick_objects`

---

includes/media.php

Prevent possible notice if image doesn't exist

---

classes/fields/file.php

Use `pathinfo` to properly validate file extension

---

classes/fields/pick.php

Fixes #5839 
Fixes #5859 
Fallback to default display field is custom option is invalid.

Relationships: Fallback to default display field

---

components/Templates/includes/functions-view_template.php
tests/phpunit/includes/Shortcodes/Test_Each.php

Fixes #5882 
Caused by PR: #5855
Prevent the media Pod from being overwritten.

Store media pod in separate variable to prevent overwrite

---

classes/PodsI18n.php

Fixes #5888 
Fixes the AJAX results for relationship fields based on query.

Fix i18n Pods relationship AJAX search

---

classes/PodsField.php
classes/fields/boolean.php
classes/fields/color.php
classes/fields/datetime.php
classes/fields/email.php
classes/fields/file.php
classes/fields/link.php
classes/fields/number.php
classes/fields/oembed.php
classes/fields/password.php
classes/fields/phone.php
classes/fields/pick.php
classes/fields/text.php
classes/fields/website.php

Fixes #1106 
Adds a new filter: `pods_field_validate_{$type}`

New filter `pods_field_validate_{$type}`

---

components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php

Allow the_excerpt to be used as custom filter on singular pages

---

classes/fields/file.php

This will probably trigger the correct filter of the Network Media Plugin
Fixes: #5748

Include the post type in attachment save

---

readme.txt

2.7.25 changelog

---

components/Templates/includes/element-pod_reference.php

Fix php error

---

classes/fields/file.php

[Pods 2.8 Bug] PHP warnings on file.php

---

ui/js/blocks/pods-blocks-api.min.asset.json
ui/js/dfv/pods-dfv.min.asset.json
ui/js/dfv/src/admin/edit-pod/main-tabs/dynamic-tab-content.js
ui/js/dfv/src/components/connected-field-wrapper.js

Fixes Relationship fields connected to other Pods. 
Fixes #5966.
Replicate issue in #5966, after saving the value will still be correct. 
-- Bug: Fixes issue where Relationships were not being set correctly. 
- [] My code includes automated tests for PHP and/or JS (if applicable).

Fixes issue with relationship fields to other Pods not working

---

classes/PodsAdmin.php
classes/PodsInit.php

Fixes #5793 
TODO: Field dependencies for input/text fields.

WP 5.5: default term option for taxonomies

---

classes/PodsMeta.php

Updated PR from #5919 
Fixes #5879

Fix default field value populating

---

classes/fields/file.php

Co-Authored-By: Scott Kingsley Clark <709662+sc0ttkclark@users.noreply.github.com>
Only compare file extensions lower-cased
Fixed #5975

Support capitalized file extensions

---

classes/fields/file.php

Currently we only support the default WP upload structure.
It would be awesome if we would support custom directories.
This PR is to allow custom directories within the uploads folder ONLY!
Fixes #6021 
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See '....'

Plupload custom upload directories (within wp-content/uploads/)

---

classes/PodsUI.php

In case fields['reorder'] is empty, don't override with an empty array and fallback to fields['manage'].
#6034 
1. Import:
```json
{"meta":{"version":"2.7.28","build":1622402497},"pods":{"161639":{"id":161639,"name":"top_content","label":"Top Content","description":"","type":"pod","storage":"table","object":"","alias":"","fields":{"post_topcontent":{"id":161645,"name":"post_topcontent","label":"Post","description":"","help":"","class":"","type":"pick","weight":0,"pick_object":"post_type","pick_val":"post","sister_id":"","required":"1","unique":"0","oembed_enabled_providers_collegehumorcom":"0","oembed_enabled_providers_facebookcom":"0","oembed_enabled_providers_funnyordiecom":"0","oembed_enabled_providers_hulucom":"0","oembed_enabled_providers_instagramcom":"0","oembed_enabled_providers_ph …
```

Fix Error: Invalid Configuration - Missing "fields" definition in Reorder page

---

classes/PodsUI.php

Missed some allowed URL parameters.
Fixes #6039

Fix sorting URL's for ACT

---

classes/PodsInit.php

Fixes #5304
- ~~My code includes automated tests for PHP and/or JS (if applicable).~~

Fix post type archive visibility

---

classes/fields/datetime.php

Support timezones for time fields

---

classes/PodsInit.php
classes/PodsMeta.php
classes/fields/avatar.php
components/Templates/class-pods_templates.php
init.php
package.json
readme.txt

Just a one-fix release to resolve PHP notices on the Widgets screen.

Pods 2.7.30

---

init.php

Update Primary Branch header so Git Updater will work 😉

Update Primary Branch header

---

classes/fields/file.php

Allows all Pod types for plupload context and enhances support for Posts.
Fixes: #6146

Improve Plupload item context

---

classes/fields/file.php

Improvement on back compat in #6147

Back Compat: Improve Plupload item context

---

classes/PodsMeta.php
includes/general.php
init.php
package.json
readme.txt

Fixes for pods_group_add() basic handling

---

ui/js/dfv/src/components/iframe-modal.scss

Improve modal offset
Fixes #6364 
**Before:** 
**After:**

Overwrite WP core max values and set same offset as media modal.

---

ui/js/blocks/pods-blocks-api.min.asset.json
ui/js/dfv/pods-dfv.min.asset.json
ui/js/dfv/src/pods-dfv.js

Sets up Pods DFV hooks instance, and adds an action after init has completed. 
Enhancement: Sets up Pods DFV hooks instance, and adds an action after init has completed.

Start Pods DFV hooks

---

classes/fields/file.php
package-lock.json
package.json

Prevents error on strpos (L499)
Fixes #6543 (confirmed)

Remove empty values

---

package-lock.json
package.json
src/Pods/Integrations/Polylang.php

Adds a relationship type for PLL languages.
@sc0ttkclark Should this be defined as a simple relationship?
Fixes #6540
1. Install Polylang and create some languages
2. Add a relationship field
3. You should see a new group "Polylang" with a "languages" relationship type.
4. In terms of storage it should simply store as a taxonomy relationship.

Allow language relationships for Polylang

---

includes/general.php

This PR wraps the return of `pods_by_title()` through `pods_v()` to trigger filters and enable translation integrations to convert the ID.
Fixes #7141

Run post/page ID through pods_v to trigger filters

---

.github/workflows/php-compatibility.yml
.github/workflows/php-phpcs.yml

I've noticed that the [PHP Compatability](https://github.com/pods-framework/pods/actions/workflows/php-compatibility.yml) and the [PHP CodeSniffer](https://github.com/pods-framework/pods/actions/workflows/php-phpcs.yml) workflows have been consistently failing for the last weeks due to what appear to be a yaml syntax error:
```
A sequence was not expected
Unexpected type 'SequenceToken' encountered while reading 'job phpcs-compatibility'. The type 'MappingToken' was expected.
```
This PR then attempts to fix this yaml issue for both workflows and also uses the `secrets` key for better semantics.
n/a
1. Go to the actions part of this PR and see if the workflows now succeed (or at least won't fail due to this yaml syntax error)

Fixed(CI): Fix PHP Compatability & PHP CodeSniffer workflow by using correct yaml syntax and `secrets` instead of `env`
