ui/js/jquery.pods.js
Anything unchecked that was boolean in the admin interface would not get sent over in ajax query
Fixes #2610
=> Let jquery use .pods-form-ui-field-type-boolean also

ui/admin/form.php
I believe this is what is intended, otherwise around line 510 $group gets blown away
Fixes #2560
=> Change $group to be reference

classes/PodsAPI.php
I think the only case this gets hit is for custom taxonomy that isn't table based, since there is no pod associated
with it.
Fixes #2620
=> Make sure related_items are only cached for valid fields

ui/fields/codemirror.php
Apparently around CodeMirror 3.0 they dropped onBlur.  So the value wasn't being saved
=> Change CodeMirror to not use onBlur

classes/Pods/ClassLoader.php
Two distinct but related issues here.  First the code would try to alias classes more than once which caused php to complain that the class already existed.  Second the autoloader would try to 'require' files more than once which caused php to complain.
Fixes #2721
=> Make sure autoloader doesn't load the same class more than once

classes/fields/pick.php
If pods_register_related_object() is called late in the game then the objects aren't actually added to the array
because the optimizations added for 2.5 keep the tables from constantly being rebuilded.  This patch lets the items to be added without doing a full rebuild.  Also, a force rebuild before would have loaded the transient and thrown the data away.
Fixes #2737
=> Properly build related object table

classes/PodsAPI.php, classes/fields/currency.php, classes/fields/number.php
This seems like a more sane fix to so many of the bugs related to default values. If
someone really wants to make 0, 0.00, etc. the default let them force it via the "Default
Value" attribute
=> Don't force a default value in a format function

classes/PodsData.php
The incorrect order in array_merge causes old data being cached instead
of new one from DB.
=> Fixed #1786, Pods 2.x, fixed the merging data in fetch function.

classes/Pods/Data.php
The incorrect order in array_merge causes old data being cached instead
of new one from DB.
=> Fixed #1786, Pods 3.0, fixed the merging data in fetch function.

classes/Pods/View.php
This fixes issue #2658 
The removed trimming was causing issues on windows network-mounted filesystems. the function realpath() already does this for us.
=> Removing double-slash trimming

classes/PodsUI.php
=> Add $ui[‘sql’][‘select’] support for find() on SQL-based PodsUI instances for #2880 in 2.x

classes/Pods/UI.php
=> Add $ui[‘sql’][‘select’] support for find() on SQL-based PodsUI instances for #2880 in 3.0

.travis.yml
this removed 8 builds / run
which saves nearly 2 hours per UT session
#2782
=> travis-ci: only build php nightly with latest stable wordpress

classes/fields/file.php
#2995
We were using `esc_url` after handlebars escaped it, so it was always coming out as `http://icon`
Not sure if there are other instances where this could be a problem, but it fixed the issue for me in the CPT editor.
Assigning to @sc0ttkclark to consider the ramifications of this change and worry about any possible side-effects.
=> Don't over escape icon URL in file fields previewer

includes/general.php
Fixes #2932 for the 2.x branch (props @str)
=> Fixes #2932 for the 2.x branch (props @str)

includes/general.php, tests/includes/tests-shortcodes.php
Shortcodes currently use 'pagination' for two contexts (display and data) but if `page` or `offset` is supplied, it's only *meant* for one context (display).
=> Fix for pagination handling in shortcodes

components/Templates/includes/functions-view_template.php
2.x branch patch for #3018
Needs review.
=> Fixes for #3018, `[each]` tag traversal does not work with taxonomy (2.x)

classes/Pods.php
=> Issue #2779: `permalink` field traversal has only been working for post types (2.x)

classes/Pods.php
=> Issue #2779: `permalink` field traversal has only been working for post types (3.0)

composer.json
was not used
needs phpunit export
could also be replaced by php codesniffer or scrutinizer
=> composer: remove coveralls

ui/admin/setup-edit.php
Issue #3194: Attempting to delete pod from edit page results in fatal error (missing nonce?)
=> Add nonce and text translation to delete link in pod edit sidebar.

classes/PodsInit.php
When a post was scheduled, the status message displayed at the top of the edit post page was malformed, where the string placeholders were numbered
=> Fix scheduled post preview message/URL

classes/PodsAdmin.php, ui/css/pods-admin.css
Made some minor grammar changes, linked to rest api plugin on wordpress.org, and added a css class to target the rest api alert when no dependencies are available.
=> Fixes to REST API tab

ui/admin/setup-edit.php, ui/css/pods-admin.css
WP 4.4 removed h3 as a pre-styled tag. Changing tag to an h2 resolves the issue. #3270
=> Change markup to support css in wp 4.4

classes/PodsAdmin.php
When clicking the link in the admin, I noticed it hit a 404. Replacing
with the WordPress developer page for Dashicons
Fixes #3271
=> Update Dashicons Link

classes/cli/PodsAPI_CLI_Command.php
This time in the right branch :-)
It would be nice to be able to clear the pods cache from wp-cli.
Added a command to the pods api wp-cli command.
=> added clear cache command

classes/fields/number.php
Fixes #3527
Use html_entity_decode to convert separator as it is a html entity
=> *#3527 Use html_entity_decode to convert separator

includes/data.php, includes/general.php
Related to #3242 and #3526
This provides a method to allow i18n plugins to return a different post id. There might need to be other places this filter is called or additional methods might need to be called depending on which
translation plugin is used.
=> Create new 'post_id' method for pods_v

classes/fields/currency.php
=> Don't add space to currency names that use HTML encoding

classes/fields/time.php
Related to #3488
If 'Allow empty value' is unchecked and a value is not passed it will default to current time, but it will still accept 00:00:00 as a valid value
=> Allow midnight (00:00) as valid time

classes/PodsAPI.php, classes/fields/pick.php
Fixes #3572 and #3506 
`[pods]` shortcodes, Pods() objects, and get_post_meta instances should work properly.
=> Polylang fixes and cleanup

classes/PodsMeta.php
Add $metabox[ 'args' ][ 'group' ][ 'fields' ] = apply_filters( 'pods_meta_post_fields', $metabox[ 'args' ][ 'group' ][ 'fields' ], $id,  $post, $metabox, $pod  );
to classes/PodsMeta.php below $pod = self::$current_pod; line:987 so I can filter fields to display for each page.
=> feature/3520 - filter the pods metas to display

classes/PodsForm.php, classes/fields/link.php, classes/fields/website.php, ui/css/pods-form.css, ui/fields-mv/js/pods-fields-ready.min.js, ui/fields/link.php, ui/js/pods-link-picker.js
See: https://github.com/pods-framework/pods/issues/2655
New PR for 2.7 (old: https://github.com/pods-framework/pods/pull/3588)
Adds a link field type with options to add a link with a title and
target.
Validation similar to website field.
UI has the option to open the WordPress link modal to search for
existing content and autofill the fields for this field.
pods_field_display() will show a formatted link.
=> New Link field with WP link modal

classes/fields/wysiwyg.php
Related: https://github.com/pods-framework/pods/issues/3549
=> WYSIWYG editor type option is used as dependency by the editor options

ui/admin/setup-edit.php
Handy to add meta/option boxes to the side of the pod edit page
Bringing over PR from #3609
=> Allow extra meta/option boxes to be added in the pod-edit screens

ui/css/pods-admin.css
Related: https://github.com/pods-framework/pods/issues/3648
I can't find any actual need of the `margin-left` property. It only breaks alignment.
Changed `max-width` to `25em` to match with the default WP setting fields css class "regular-text" as seen in the general settings.
This:
Becomes this:
=> Improve field alignment on setting pages

classes/PodsMeta.php
Fixes: https://github.com/pods-framework/pods/issues/1614
=> Do not display metagroup if all fields are set to hidden.

classes/PodsAdmin.php, classes/PodsInit.php, ui/admin/setup-edit.php
Fix for:
https://github.com/pods-framework/pods/issues/3676
https://github.com/pods-framework/pods/issues/3677
=> Taxonomy capabilities + No more hardcoded tax settings

classes/PodsAdmin.php
Fixes #3710 
Filters:
`'pods_admin_setup_edit_' . $type . '_additional_field_options'`
`'pods_admin_setup_edit_additional_field_options'`
(PR is used for #3634, would also improve https://github.com/pods-framework/pods-seo/pull/6)
=> Filters to modify additional field options

classes/PodsRESTHandlers.php
=> Don't override REST base for basic included post types from WP-API

ui/js/jquery.pods.js
Discussed in [Issue 3771](https://github.com/pods-framework/pods/issues/3771).
=> Changed from deprecated .live() to .on().

ui/js/jquery.pods.js
Check if this element is a child from an 'Advanced Field Options' group.
If so, set the value to empty if this is not the current field type group.
Fixes dependency compatibility of https://github.com/pods-framework/pods/issues/3707 and https://github.com/pods-framework/pods-seo/pull/6
=> Validate field option dependencies based on location within in tabs

classes/PodsAPI.php, ui/admin/settings-tools.php
This solves the issue when running multisite and you’ve got an object cache drop-in that won’t flush cache for multisite when wp_cache_flush is called
=> When preloading config after flushing cache, bypass cache

classes/PodsAdmin.php, classes/PodsInit.php
Fixes https://github.com/pods-framework/pods/issues/3848
@todo for 2.7
Check compat with https://github.com/pods-framework/pods/pull/3669 since these are at the same lines in PodsInit.php (around L696)
=> `show_in_menu` option for taxonomies

classes/fields/pick.php
What is happening in the situation that a data_callback is set (like with a predefined list) is the check in PodsField_Pick->input() that sets $ajax properly is not working because
self::$field_data[ 'id' ] == $options[ 'id' ] is not true since the $field_data contains data from the previous field that was loaded
Resolves #3862
=> Make sure self::$field_data is set in all cases

classes/fields/file.php
- Only updates if the parent isn't set yet.
- Small rewrite of the `save` logic for the file field.
Fixes/Related: https://github.com/pods-framework/pods/issues/3808
Possible improvements:
- Delete the attachment when removing >> Can give some problems if the file is used multiple times in the post... I personally don't think we should do this. (Related: https://github.com/pods-framework/pods/issues/3793)
=> Update the attachment parent if updating a post type

classes/PodsUI.php, ui/css/pods-admin.css
Adds the required classes and attributes to form nice responsive view for PodsUI pages.
- Adds the `column-primary` class to the first field (ignores a possible first checkbox field)
- Adds the `data-colname` attributes
- Adds our own `column-secondary` that can be passed with a field when calling PodsUI. A secondary field will always be show so the user won't need to toggle
- Reformatted the code to work with arrays of classes instead of strings. (Easier to manage)
**Before:**
**After:**
**Before:**
**After:**
=> Patch the responsive markup WP edit.php UI to Pods UI

classes/PodsData.php, components/Builder/modules/field/PodsBuilderModuleField.php, components/Builder/modules/form/PodsBuilderModuleForm.php, components/Builder/modules/list/PodsBuilderModuleList.php, components/Builder/modules/single/PodsBuilderModuleSingle.php, components/Builder/modules/view/PodsBuilderModuleView.php, components/Markdown.php, deprecated/deprecated.php
=> Fix PHP7 Compatibility issues

classes/PodsAPI.php
=> \PodsAPI::save_relationships does not clear \PodsAPI::$related_item_cache

ui/fields/plupload.php
This change fixes #3763 by making Plupload instances available to other code by storing them in `windows.pods_uploader[id]`.
It also removes `<?php echo esc_js( pods_js_name( $attributes[ 'id' ] ) ); ?>` from the variable names used in this scope, as these variables are only available in this closure.
=> Keep Plupload instances in `windows.pods_uploader`

classes/PodsAPI.php
Fixes #3477
When editing an object's bidirectional taggable relation, and you add a related object that doesn't exist, the reverse relation is now correctly set up.
I just learned about Pods today so this fix could be completely off base, but it works for me.
The problem was that the `save` method for the `pick` field was being passed the original array of ids instead of the new variable that contains the id of any newly added objects.
(I'm using Pods 2.6.6 and Wordpress 4.5.3)
Cheers!
=> Properly update bidirectional taggable relations

classes/fields/avatar.php, classes/fields/boolean.php, classes/fields/code.php, classes/fields/color.php, classes/fields/currency.php, classes/fields/date.php, classes/fields/datetime.php, classes/fields/email.php, classes/fields/file.php, classes/fields/html.php, classes/fields/number.php, classes/fields/paragraph.php, classes/fields/password.php, classes/fields/phone.php, classes/fields/pick.php, classes/fields/slug.php, classes/fields/taxonomy.php, classes/fields/text.php, classes/fields/time.php, classes/fields/website.php, classes/fields/wysiwyg.php
=> Make field labels translatable

includes/media.php
Noticed that having multiple audio files using this on one page played the same file, turns out the 'src' wasn't getting passed into wp_audio_shortcode
=> Pass audio_args to audio shortcode

includes/data.php
Fixes #3823 
About sanitizing `$wpdb->esc_like()` input:
> This needs to be done **after** using $wpdb->esc_like(), to ensure correct and secure slashing of the string.
https://codex.wordpress.org/Class_Reference/wpdb/esc_like
=> Fix slash problem with LIKE statements

classes/PodsForm.php
See #3940 
Could'nt fix this more "neat" due to the global use of the `_label.php` file in the fields.
=> Fix double help qtip when using single checkboxes (boolean type)

classes/PodsAdmin.php, classes/PodsInit.php
Quick fixes #3896 
For Pods 2.7 (or later) I think we should revisit the capability handling for Pods.
Since WP 4.7 there are two default capabilities for taxonomies: `category` & `tag`, just like with posts (`post` & `page`).
I'll create a new ticket for this (not a high priority issue).
=> Add new singular capabilities for taxonomies (WP 4.7)

classes/fields/currency.php
=> Enhance Currencies + add new

classes/PodsData.php
Ran into this issue myself.  The field traversal tests currently do not cover testing the 'search' type of find.
Search works fine on Table based CPT or ACT but not on Meta based CPT.
Fixes #3858
=> Search the proper SQL column with 'search' and meta based CPT

components/Templates/includes/functions-pod_reference.php
Fixes #3370, #3992
This cleans up the code quite a bit.  Still not perfect and the ordering might need to be adjusted a bit but it will keep everything from exploding.
Related to #3370
Also includes #3992 since it covers the same functions
Replaces #3999 which was a PR from my own fork
=> Tame the template reference recursion

components/Templates/includes/functions-pod_reference.php
Currently any logged in user can execute this AJAX action which would allow them to return a list of the names of all of the elements on any Pod.
Not a major issue, but should be protected anyways.
=> Only allow admins access to the 'pq_loadpod' AJAX action

includes/general.php
In this new way we don't unset all of the un-needed shortcodes, just add a temporary filter that stops it from executing.
=> Change method of short circuiting WordPress shortcodes

classes/PodsAPI.php
get_posts() returns an array with the results even if you are only asking for 1 post per page.
=> Allow pod_exists() to work if passed a post_type name

classes/Pods.php
Issue #4040 
When using shortcodes with PDF attachments `._src` returns an image since WP 4.7.
With this fix it will return the PDF url.
Getting PDF generated images (WP 4.7) images is still possible using `._src.image_size` or `._img`.
=> No default image size for non-images. `_src`

.travis.yml
https://make.wordpress.org/core/2017/05/25/hhvm-no-longer-part-of-wordpress-cores-testing-infrastructure/
=> travis-ci: remove hhvm

classes/PodsAdmin.php, readme.txt
Supplying spelling corrections for incorrect strings I came across while translating en_CA.
=> Minor Spelling Fixes

classes/PodsAPI.php
#4313 
I added a function `array_filter_walker` and a few extra steps to ensure backwards compatibility.  This may be unnecessary but since the multidimensional array is generated by the name properties in the fields HTML it seemed prudent not to affect that for the sake of making this a quick fix.  Everything should perform as expected now, regardless of the array structure.
=> Fix: multi-file fields save causes array to string conversion notice.

components/Templates/includes/functions-view_template.php
Needs further tests built to make sure this doesn't break anything else.
Related to #4403
Currently the code appears to expect:
```
[if rel_field.permalink]
{@permalink}
[/if]
```
When it appears that the desired behavior is:
```
[if rel_field]
{@rel_field.permalink}
[/if]
```
This should allow both behaviors to work, in the first case the context is "switched" inside the if to the object related via rel_field.  In the second case the context remains with the original object but allows it to be referenced via dot traversal.
Need to build tests for the other frontier related shortcodes to ensure more isn't broken by this
=> Don't strip field traversal if the specified field does not contain a period

classes/Pods.php, classes/PodsAPI.php, classes/PodsData.php, classes/fields/pick.php
What's happening is that the 'where_default' is always getting used because the query is a post_type but does not include the post_status in the where, so PodsData->query_fields() was using the
'where_default' param which wasn't getting passed through properly.
Related to #4437
=> Allow where_default to pass through SQL queries

components/Templates/includes/functions-view_template.php
Complicated issue with nested shortcodes that fall under non-pods shortcodes (ie: inside a builder shortcode).  The frontier output isn't available to the typical WordPress do_shortcodes since
it is obfuscated in base64.
Also eliminates some code duplication, seeing that same array of tags all those times was driving me crazy.
Related to #4303
Reimplementation of #4373 based of release/2.7
=> Simplify logic for frontier [if] shortcodes (again)

classes/Pods.php
Creates new WordPress filter 'pods_pre_do_magic_tags'.  By default returns false which continues on with normal execution, if something other than false is returned that value is returned.
Resolves #4447 
Thought I opened a PR on this but I guess I just created the branch
=> Allow magic tags engine to be replace via WordPress filter

classes/PodsInit.php
To make things like https://github.com/pods-framework/pods-export-code/issues/4 easier to accomplish.
=> Move post type / taxonomy registration

components/Templates/includes/functions-view_template.php
Relationships to things like Pods don't really have data to traverse into with each.  So here it creates a pseudo magic tag handler that uses data from the array instead of from a Pod.
This is really closer to how all tags should be handled anyways and lines up closer to how Twig handles things.
Related to #4484
=> Allow handling of arbitrary data that aren't Pods

ui/front/form.php
Fixes #4514
The dependency tree for the `pods` script has grown via its dependency on `pods-dfv` resulting in a script load-order bug.
=> Inline `wp_print_scripts` causes load order problems with script dependencies

classes/PodsAPI.php, includes/general.php
Related to #4540.  This will allow the JS redirect to be displayed as well as let the footer be printed which will keep the original issue from happening.
=> Make form submission not direct and then die

components/Templates/includes/functions-view_template.php
ACTs have a lowercase 'id' but while parsing the [each] template tags only the uppercase 'ID' was checked.
=> Fixed: Relationships to Advanced Content Types in [each] template tags.

ui/front/form.php
=> `ajaxurl` was being locally scoped; remove superfluous document ready wrappers

init.php
Related:
https://wordpress.org/support/topic/pods-breakage-due-to-new-php-mysql-requirements/#post-9762357
=> Set minimum MySQL version to 5.1, at least it's better than 5.0

classes/PodsUI.php
=> Missing thickbox styles for `PodsUI::filters()`

composer.json
=> mockery 1.0 requires php >=5.6.0; downgrade to 0.9 for now

classes/PodsUI.php
The `pods_ui_message` filter hook in `pods_ui` allows to change the message being printed in the admin notice box. In case the returned message is `null` the box shouldn't be printed at all.
=> Avoid printing null message in PodsUI

components/Templates/includes/functions-view_template.php
In the else case which was handling users before the Pod extended data was not available because calling Pods->field() on a relationship to a user field only returns the WordPress core fields
Related to #4752
=> Allow user-meta (and other extended Pods) to work in templates

includes/general.php
=> Fix copy/paste mistake for `search` param in Pods shortcode

classes/fields/time.php
Change `empty_value` to the empty string and override `format_value_display` in the time field to allow midnight as a valid time and allow a proper empty value to be set (where allowed).
Fixes #4937, #3488
This is hopefully just a final patch to fix a couple issues with the time field before converting date/time/datetime to DFV.
=> '00:00:00' is midnight and a perfectly valid time value

phpcs.xml.dist
Pods 2.7 requires WP 4.5 and PHP 5.3.
=> Update phpcs.xml.dist for WP 4.5 and PHP 5.3

bin/phpcs-audit.sh, bin/phpcs-autofix.sh, phpcs.xml.dist
Extends #4975 with a few more changes to centralise PHPCS args into `phpcs.xml.dist`.
See https://github.com/pods-framework/pods/pull/4975#discussion_r192555632.
=> Extend PR #4975

phpcs.xml.dist
Add prefix and textdomain to enable further checks.
See:
- https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#naming-conventions-prefix-everything-in-the-global-namespace
- https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#internationalization-setting-your-text-domain
=> Update phpcs.xml.dist with prefix and textdomain

components/Templates/includes/element-view_template.php
Wordpress will already call `esc_textarea()` if rich edit is off, so don't double-escape when the visual editor is disabled.
Fixes #3462
=> Code Editor for Pods Template double-escapes HTML when Visual Editor is OFF in WordPress

phpcs.xml.dist
Adds two args to `phpcs.xml.dist` to make the PHPCS output easier to read.
Fixes #4985.
See #4985.
Improvement: Make PHPCS output easier to read #4985 (@GaryJones)
=> PHPCS: Add colors and basepath args

classes/PodsAPI.php, classes/PodsAdmin.php, classes/PodsInit.php, components/Helpers.php, components/I18n/I18n-polylang.php, components/I18n/I18n-wpml.php, components/Pages.php, components/Templates/Templates.php, components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php, ui/admin/setup-edit.php
Addresses some I18n code standards violations.
- WordPress.WP.I18n.MixedOrderedPlaceholdersText
- WordPress.WP.I18n.UnorderedPlaceholdersText
- WordPress.WP.I18n.TextDomainMismatch
- WordPress.WP.I18n.NonSingularStringLiteralDomain
- WordPress.WP.I18n.NonSingularStringLiteralText
Makes it easier for translators to re-order placeholders in their locale, adds several string to the `pods` textdomain.
See #4982.
Code standards improvements. See the individual commits for more info.
Improvement: Addresses some internationalization code standard violations #4982 (@GaryJones)
=> PHPCS: Fix some I18n violations

ui/fields/_label.php
Fixes #4614.
See #4684 (props @davidatwhiletrue for original PR). This PR just addresses the merge conflict. I checked out @davidatwhiletrue's branch, cherry-picked his commit, and then fixed the merge conflict and committed, so that @davidatwhiletrue's contribution is retained.
Manually checking for the presence of the tooltip icon, before and after applying patch.
Before: Label just says "Help" in Spanish:
After: No tooltip icons present for redundant help text:
Bug fix / UI improvement (non-breaking change which fixes an issue)
Improvement: Check for localized 'help' before adding tooltip #4612 (@davidatwhieltrue)
=> Labels: Check for localized 'help' before adding tooltip

classes/cli/Pods_CLI_Command.php
WP-CLI errors should only be thrown if Pods / Pods Items are NOT valid or do NOT exist.
Original code committed in https://github.com/pods-framework/pods/commit/c1d39bc09b452bfb197ed66a590e130a63f7acc9.
Fixes #4989.
Running command-line calls locally.
Before and after the code fix:
Bug fix (non-breaking change which fixes an issue)
Fix: CLI: Fix missing negation on valid & exists checks #4989 (@GaryJones)
=> CLI: Fix missing negation on valid & exists checks

ui/js/jquery.pods.attach.js
Use `.length` property instead.
Fixes #3898
Only one instance of `size()` existed, compared to the two mentioned in #3898.
=> JS: jQuery.fn.size() is deprecated

classes/fields/pick.php
Introduce `PodsField_Pick::is_simple_tableless()` method to simplify the `can_ajax()` method to a single line.
Fixes #4993.
Manual inspection.
Code refactoring.
=> Refactor PodsField_Pick::can_ajax()

classes/PodsInit.php
https://core.trac.wordpress.org/ticket/44142#comment:14
Changelog: Fixes cases where there may be "500 Internal Server Error" messages when Pods clears it's caches and flushes rewrites
=> Only flush rewrite rules in an admin context

components/Templates/includes/element-view_template.php
=> In-line the textarea content for Pods Templates to avoid leading and trailing whitespace

classes/PodsAPI.php, classes/PodsData.php, classes/PodsForm.php, classes/PodsInit.php, classes/PodsMeta.php, classes/PodsUI.php, classes/PodsView.php, components/Migrate-Packages/Migrate-Packages.php, components/Roles/Roles.php, components/Templates/includes/functions-view_template.php, deprecated/classes/Pods.php, deprecated/list_filters.php, includes/data.php, includes/general.php, includes/media.php, sql/update-2.0-beta.php, sql/upgrade/PodsUpgrade.php, tests/phpunit/includes/testcase.php, tests/phpunit/includes/tests-traversal.php, ui/admin/setup-edit-field-fluid.php, ui/fields/date.php, ui/fields/datetime.php, ui/fields/slider.php, ui/fields/time.php
Fixes: #5021 
Fixes a total of 102 errors and 0 warnings found in 24 files.
This sniff checks for assignments that are not the first block of code on a line - typically chained setting of variables, or assignment inside conditions.
See #3181.
Before:
After:
Code standards.
=> PHPCS: Fix Squiz.PHP.DisallowMultipleAssignments

classes/PodsUI.php
Fixes #5043
Fixes 'others' capability checks for current_user_can pods_{$action}_{$pod} vs pods_{$action}_others_{$pod} capabilities.
Fixes the 'others' capability checks in PodsUI restrict handling
=> Fix 'others' capability checks for current_user_can in PodsUI

classes/fields/time.php
=> Prior to PHP 5.5, 'empty()` only supports variables

classes/Pods.php
Allows for keys to be maintained for relationships. The default functionality is to do an array_values() on the returned value.
Later: Add support for output type `ids=>names`
Added: Support for Pods::fields() argument `keyed` which when set to true will return the array for relationship fields with the IDs used as keys.
=> Add support for Pods::field() 'keyed' argument

classes/PodsI18n.php
Instead of relying on `get_current_screen()` this patch switched to the use of the `$_SERVER['SCRIPT_NAME']` wrapped in `basename()` to get the current screen base.
The WP_Screen object isn't available until after `admin_init` which apparently is too late.
Fixes: #5060 
Fix compatibility issue with Polylang & WPML when getting the current language from the edit post and edit tax pages.
=> i18n: Fix compat issue with `get_current_screen()`

classes/PodsAdmin.php
=> Always enqueue the DFV script by default if in the admin

rollup.config.js
Fixes #5120
This is prep for 2.8 and to (hopefully) cut down on future merge conflicts.  2.x isn't using React so this is a configuration-only change there.  These changes produce an identical compiled bundle under 2.x so this PR needs no changelog entry.
=> Update build tool configurations in prep for 2.8

ui/front/form.php, ui/js/jquery.pods.js
Fixes #5136 
I've tested this on a dev environment where I was using PodsForm on the front end. There was a need for conditionals (currently only manually configured).
I also verified this doesn't break the admin side of Pods. No issues found.
The changes are only in code. No interface changes has been made, those would be related to #609 
**Enhancement:** Add pods conditional logic handling on frontend forms.
=> Frontend forms conditional logic

classes/PodsAPI.php
Fixes #2042
Simple values that contained Commas would never save correctly due to an explode if it was not provided in an array. This would affect single select fields but not multi select for that very reason.
Fix: Single simple relationships with commas in the text no longer save as empty
=> Fix explode issues with comma characters

classes/PodsComponents.php
Fixes #5206 
- Only disable components when using PODS_TABLELESS if the component is relying on custom tables.
=> Fix issue with pods tableless access to components

includes/data.php
Fixes #5210 - PHP Warning for array key `pods_rel` not found.
- Fix PHP Warning
=> Use `pods_v` to prevent PHP Warning

ui/fields/checkbox.php
Fixes #4961 
The "readonly" attribute only prevents the "value" attribute from changing which is not what we want in the case of checkboxes as interacting with a checkbox changes its `checked` attribute instead which is why we need to do this:
1. Add `disabled="DISABLED"` to the checkbox.
2. As a consequence of 1, even if the checkbox default value is set to `1`, the value stored will still be `0` since disabled inputs are not submitted.
3. To fix 2 we add a hidden input immediately after the checkbox only when the checkbox should be checked.
4. The hidden input will have the same name and value as the checkbox and will override it since it appears later in the html hierarchy. A bit hacky but avoids name clashes with other fields and the need for special-case back-end code.
| Default …
=> #4961 - Fix read-only not having any effect on checkbox fields

classes/PodsView.php
pods_is_admin() check was not necessary here, it should only run if the nocache break is attempted for use.
Fixed: Remove unnecessary user query on each load
=> Avoid extra user queries when not necessary

classes/PodsData.php
Needed for when hooking into shortcode output filter to show total found information about Pods query. Otherwise, there's it shows the wrong total found referencing the wrong query.
Tested "live"
Added: New `pods_data_auto_calculate_total_found` filter can be set to true to auto-calculate total_found() number right away after a Pods::find() query runs, defaults to false
=> Add ability to auto calculate total_found

classes/fields/currency.php
Sorted alphabetically by name, added Indonesian Rupiah (fixes #5247), and went ahead and added the US Cent for giggles, I think there's still a use for it.
* Added: Indonesian Rupiah (Rp) currency support [5247]
* Added: US Cent (¢) currency support
=> Clean up currency list and sort them alphabetically

classes/PodsAPI.php, includes/data.php
Fixes user, comment, and media serial comma usage.
Fixed: Serial comma display works again for Users, Comments, and Media relationships when used in Pods::display() and magic tag templating without specifying the object field you want to display.
=> Fix table info handling in pods_serial_comma

ui/admin/setup-edit-field.php
=> Manage Fields: avoid stripping any intentionally inserted literal HTML

components/I18n/I18n.php
This PR will add the new 5.0 labels to the list in the i18n component and enhances the label replacement code. From now on it will also append translation labels even if the label doesn't exist in the original language.
It will also fix an issue with the user locale. If the function exists it will use `get_user_locale()` instead of `get_locale()`.
Fixes: #5259
- Add WP 5.0 post type labels to Pods i18n component.
- Add integration for the user locale option in the Pods i18n component.
=> Pods i18n: WP 5.0 labels + compatibility with WP 4.7+ get_user_locale()

classes/PodsView.php
This fix resolved issues where Pods Option Cache does not properly function and stores extra unnecessary objects when using an external object cache.
=> Fix option cache handling when using external object cache

Gruntfile.js
=> Remove "2.x" prefix from the release tag

classes/fields/datetime.php
=> Always use `date_i18n` to ensure proper localization.

ui/js/pods-dfv/src/components/field-container.js
React will treat an input as an uncontrolled input if the value state is set to null or undefined.
=> Field Container: Default to empty string for value if it is passed as null or undefined

includes/general.php
If you have a `tcp://` session handler, the `session_id()` check would never run and `@session_start()` would be executed even though a session was already present.
Affects `tcp://` session handlers, like memcached.
The `session_start` conditional was checking if you have a `tcp://` handler, and then proceeded to start a session. This is because the conditional was exiting when `tcp://` was detected, and the `session_id()` condition check further down never happened. 
Due to this the `session_id()` check was only executed for file based session handlers.
Moved `session_id()` check outside the big conditional, so it's always executed.
Fix: Stop duplicate session starts for tcp based session handlers
=> session_id conditional never checked for tcp sessions

classes/fields/pick.php
Advanced search filter in Admin UI was giving (after choosing any criteria):
Warning: Invalid argument supplied for foreach() in .../wp-content/plugins/pods/classes/fields/pick.php on line 1818
Using:
Pods - Custom Content Types and Fields: 2.7.9
WordPress Version: 5.0-beta5
PHP Version: 7.2.12
IF check before foreach loop to test if $check_value variable is an array or not.
Avoid PHP warnings by removing unused $check_value logic in PodsField_Pick
=> Fix foreach check_value loop by checking first if it is an array

classes/fields/currency.php
Fixed #5386
- Fix typo: "width" to "with"
=> Fix typo `width` > `with`

classes/PodsAdmin.php, classes/PodsInit.php, includes/general.php, sql/upgrade/PodsUpgrade.php, ui/admin/settings-tools.php
WP now has a great new Site Info area, it provides more details we could use when debugging so this adds our unique debug info to that and we can simplify our debug process going forward with that.
* Added: Add debug information for Pods to Site Health Info area
=> Add Pods debug information to Site Info area

classes/fields/datetime.php
Fixes #5382, #5402, #5403 and probably more
Currently after date/time values are stored into the database the date/time field convert them using the WordPress timezone setting (in cases where DateTime is available). This conversion is incorrect since it returns a different value than the user's input.
* Always convert database value for date/time fields with UTC timezone to maintain the actual value.
=> Always convert with UTC timezone

classes/PodsMigrate.php
FIX Import from file with absolute path
Var $path was not used, so file cannot be imported
I test this by cli pods-api import
Fix: Import from file with absolute path (@mistraloz)
=> FIX Import from file with absolute path

classes/fields/number.php
Fixes #5281 
Fixes #5215
- Removed `array_filter()` since it filtered all array values and it should only remove the decimals if empty. Also moved this code to a separate method to re-use in `pre_save()`.
- For slider input I've forced the input format to `1234.00` since the jQuery UI Slider only supports that input format.
* Fix numeric soft format issue removing decimals & numeric slider input formatting
=> Fix numeric soft format issue removing decimals & numeric slider input formatting

classes/PodsAPI.php
Fix an issue related to #5428 (reserved keywords). When extending CPT or taxonomies it gave errors on (for example) `page` post type since that is also a reserved keyword.
I've brought the `create_extend` parameter into `save_pod`. If that is set and is set to `extend` it will validate against existing CPT/Tax objects. If that name exists the name will still be valid.
No need for an extra changelog.
=> Fix issue with extending post types and reserved keywords.

classes/fields/date.php, classes/fields/datetime.php, ui/fields/date.php, ui/fields/datetime.php
Fixes #5442 
Adds a new option to change the year range for date/datetime fields.
* Enhancement: Add year range option to date & datetime fields.
=> Feature: Date/datetime year range option

classes/PodsAPI.php
Fixes: #5420 
* Fixed: Flush Pod cache before returning errors
=> Flush Pod cache before returning errors

ui/fields/datetime.php
Fixes issue since: #5442 (PR: #5443)
* Fixed: Possible issue with global jQuery var ($) for datetime field.
=> Hotfix Datetime field: Make sure $ can always be used

composer.json, tests/phpunit/includes/testcase.php
Fixes: #5468 
This will then accept `post`, `page` etc. as Pods object names.
Fixes: #5475 
- Deprecation warning for uppercase + package wimg/php-compatibility
=> UnitTests: Extend objects when using reserved keywords

classes/fields/boolean.php
Fix #5481 by adding a validate() to the boolean field.
- Create a form with a required checkbox field
- Try to submit the form without ticking the box.
Bug fix
Fix: Cannot submit a form if required checkbox not ticked.
=> Add validate method to boolean field to fix #5481

includes/data.php, tests/phpunit/includes/Bugs/Test_5254.php
The pods_str_replace() function can't handle values that are not strings.
Fixes #5254
Test included in first commit, second commit will have actual fix
Fix: Allow pods_str_replace() function to handle non-strings #5254 (@jamesgol)
=> Fix pods_str_replace

classes/PodsAPI.php
WordPress expects slashed data
Fixes issue #5366 
I can't be sure if this is going to break anything else, hopefully the tests cover enough.
=> Sanitize meta values before passing to *_post_meta functions

includes/general.php
Didn't notice this causing any issues (though who knows if there are any underlying).
Fixes #5512 
Fix: Make sure number of arguments passed to PodsMeta->save_post() is correct #5512 (@jamesgol)
=> Make sure number of arguments passed to PodsMeta->save_post() is correct

classes/PodsAPI.php
Fixes #4926 (verified by 1 user)
The table info returned made errors in the traversal logic.
It appended the lookup field id of the custom tables in the traversal array (`field_name.lookup_field_id`) which broke the get_table_info for the latter since that field doesn't exist.
Thorough testing required before merging!
=> Fix custom table relationships SQL error

classes/fields/date.php, classes/fields/datetime.php, classes/fields/time.php, ui/fields/datetime.php
Fixes: #5238 
jQuery date & time pickers both use `mm` which gets formatted wrong if used both.
This PR separates formatting conversion for date and time strings.
* Fixed: jQuery date & time picker overlapping formats.
=> Bug: jQuery date & time picker overlapping formats.

ui/fields/datetime.php
Fixes: #5488 
The close/blur events from the date/time pickers aren't always picking up manual user input (keyboard). This PR fixes that and makes sure dates are parsed through the date/time picker at any time, even is the value is empty.
* Fixed: DateTime: Always parse any manual input data.
=> DateTime: Add onClose method to always parse any manual input data

classes/PodsAPI.php
Fixes: #2360
Fixes: #5479
Closes: #3616 (Sorry @jamesgol, I think this might be a better and simpler fix)
Closes: #1943 (Old related issue)
This PR makes sure simple custom relationship options are unslashed before comparing to input data.
This needs to be done because input data is unslashed as well. If we want to correctly compare input data to available options both sides need to be the same.
=> Unslash simple relationship values to support saving quoted values

includes/general.php
If there are no query tags and no object info is supplied.
Fixes: #5598 
Currently the shortcode automatically reverts to the current post if it's in the loop.
While there is a use_current parameter it might be a nice feature to support simple shortcodes for users and taxonomies as well ([pods field="name"]).
=> Shortcode: Automatically revert to use_current

classes/fields/datetime.php, ui/fields/datetime.php
Fixes: #5534 (verified by user)
Fixes: #5544
See issue.
Everywhere we check for empty date values I've replace the array search with the is_empty() method. This centralizes the empty validation checks.
=> DateTime: Use is_empty() to centralize validation

classes/fields/number.php
Fixes: #5559 #5597
Apply unslash on format before comparing + refactor to switch statement for readability.
- Fixed: Parsing error for number format 9'999.99.
=> Fix compare 9'999.99 format

classes/PodsInit.php
Fixes: #5606
* WP 5.4 Compatibility: Add user Pod fields to privacy export data
=> WP 5.4 Compatibility: Add user Pod fields to privacy export data

components/Roles/ui/edit.php, ui/admin/form.php, ui/admin/setup-edit.php, ui/admin/view.php
WP 5.4 switched from the `poststuff` ID to a class. This PR adds the class and leaved the ID for backwards compatibility.
- WP 5.4 admin style compatibility
=> Add poststuff class for wp5.4 compatibility

classes/fields/file.php
Fixes: #5185 
- Enhancement: Add "full" to available image sizes in file fields.
=> Add "full" to available image sizes

includes/general.php
Fixes: #5580 
* Enhancement: Add `not_found` tag to the Pods shortcode to return default string if no output is empty.
=> Add `not_found` tag for shortcodes

components/Markdown.php
Fixes: #5582
Deprecated: Array and string offset access syntax with curly braces is deprecated
* Fix: PHP 7.4: Array and string offset access syntax with curly braces is deprecated.
=> Fix PHP 7.4 deprecation

classes/fields/pick.php, components/Helpers.php, components/Pages.php, components/Templates/Templates.php, components/Templates/class-pods_templates.php, components/Templates/includes/functions-pod_reference.php
Admin area shows deprecated notices when using Pods templates/helpers/pages components. Also sometimes bad pod configurations can fatal.
Fixed: Replaced hook used for meta boxes in admin for custom component integrations to avoid deprecated notices from WordPress.
Fixed: Prevented potential fatal errors on Pod Template editor screen when pod configuration is broken.
=> Fix dbx_post_advanced deprecated notices and error on page

classes/Pods.php
Currently we detect the current queried object based on the object parameters. Using instanceof would be more reliable.
=> Set type detection based on classes instead of parameters

classes/Pods.php
Fixes #5610 bug I missed in getting the correct thumbnail from an each loop.
Bug found by @jimtrue
=> Fix getting the post thumb by correct ID

classes/fields/datetime.php
Fixes: #5616 
Currently midnight (`00:00:00`) isn't supported because this value is considered empty.
This PR fixes that.
=> Allow midnight as time value

includes/general.php
Fixes: #5636 
Since in nearly all occasions themes start a loop, even for singular pages, this bug wasn't noticed.
I tested this fix by adding `[pods]{@post_status}[/pods]` in the `wp_body_open` hook, outside the posts loop and can confirm this works.
- Fixed: auto `use_current` not working correctly
=> Shortcodes auto use_current fix

classes/fields/pick.php, tests/phpunit/includes/tests-pods-data.php, tests/phpunit/includes/tests-pods-field-boolean.php, tests/phpunit/includes/tests-pods-field-currency.php, tests/phpunit/includes/tests-pods-field-pick.php
Fixes: #5637
This PR makes the serial comma optionally and disables it for the custom separator format.
I also added some simple unit tests for `pods_serial_comma()`
- Fixed: Double comma in custom pick display formats.
=> Fix pick display serial comma

classes/fields/boolean.php, tests/phpunit/includes/tests-pods-field-boolean.php
Fixes: #5643 (confirmed by user)
Fixes: #5649
PR #5550 introduces fixes for validation boolean fields from a API stand of view. This however created an issue with Pods if/else tags.
This PR fixes that and adds unit tests to make sure this won't happen again.
=> Fix [if][else] magic tags for boolean fields

components/Templates/Templates.php, includes/general.php
Fixes #5668
Backwards compatibility fix -- This now only trims the template after running, to prevent blank whitespace from being output. It will keep whitespace as is if there is any content being output.
Only trim template whitespace after running magic tag replacement if there was no content to output.
=> Fix whitespace trimming for templates

classes/PodsAdmin.php
Fixes: #5705 
Hide the "Depth" option for single response types.
=> REST field options: Only display depth for array response type

classes/fields/pick.php
Fixes: #5699
If you edit/add a taxonomy relationship the modal popup it should automatically close after edit/add.
=> Fix deprecated tax form actions

package.json
Downgrade Jest version to version supported by @wordpress/jest-preset-default
@wordpress/jest-preset-default uses a deprecated function that was removed in Jest 26, switch to Jest 25 for now.
Jest tests now pass.
Bug fix
Downgrade Jest
- [ x ] My code is tested.
- [ x ] My code follows the WordPress code style.
- [ x ] My code follows has proper inline documentation.
=> Downgrade Jest version

includes/general.php
Related: #2311
Related: #3985
Related: #4815
This PR will enhance the network check for Pods access.
Currently Pods validates the `delete_users`, just like WordPress core.
However, this is not entirely correct.
For multisite installations this check isn't valid as only actual super admins should always have access.
This PR only adds the `delete_users` cap if it's a single installation. Multisites do not check this cap.
Doing so improves the way we validate capabilities and makes it behave more similar to WP core.
=> Only check `delete_users` for single installations

classes/PodsAPI.php
In REST context, multi-level Relationship field Pods renders first level
response correctly, as an array of objects.
```
"steps": [
{},
{},
...
]
```
But further relationship fields go through `$related_pod->export()` and get
rendered as keyed object list.
```
"steps": [
{
"actions": {
"299": {
},
...
}
},
{},
...
]
```
To maintain uniform structure across the response, `$pod->export()` should
join anonymous array members camp.
```
"steps": [
{
"actions": [
{},
{},
...
]
},
{},
...
]
```
REST API requests.
Couldn't find instructions on how to make PHPUnit 8 run here.
```
$ [git:master+] phpunit
PHP Notice:  Undefined variable: test_root in /home/warmpress/wp-content/plugins/pods.git/tests/phpunit/bootstrap.php on line 21
PHP Warning:  require(/includes/functions.php): failed to open …
```
=> Nested relationship fields should render as array of objects

tests/phpunit/includes/testcase.php, tests/phpunit/includes/tests-pods-data.php
The way we assign the factory to a property isn't the same as WordPress core testcase does.
This PR fixes that.
The factory is still accessible through the property since the WordPress core testcase utilizes a `__get()` method for this.
=> Fix factory in pods testcase

includes/data.php
Fixes: #5719 
Related: https://wordpress.org/support/topic/issue-trying-to-use-shortcodes-with-pods-shortcode/
~~- My code includes PHP Unit Tests (if applicable)~~
=> Support `get_query_var` in pods_v (and thus special magic tags)

classes/Pods.php
Fixes #5781 (verified by user)
Bug caused by #5682 commit https://github.com/pods-framework/pods/pull/5682/commits/f9b46ca29299885fab3880d59fd2d2e757e51448
=> Fix preview link for ACT Pods

package.json
Separating multiple command script with a semicolon does not work on all OS.
Proper format is `&&`.
=> Fix NPM multi-commands

ui/js/dfv/src/admin/edit-pod/_edit-pod-variables.scss, ui/js/dfv/src/admin/edit-pod/main-tabs/field-groups.scss, ui/js/dfv/src/admin/edit-pod/main-tabs/field-list-item.scss
The 9px border radios isn't in line with the WP and Pods UI.
=> Pods 2.8: WP doesn't use border radius

classes/fields/pick.php
Fixes #5542 
The `IN ( $ids )` query wasn't added correctly resulting in an `OR` statement where it should be `AND`.
=> Fix selected query for autocomplete relationships

init.php
Since Pods' primary branch is now `main` in order for GitHub Updater to properly work the `Primary Branch` header needs to be added.
https://github.com/afragen/github-updater/wiki/Settings#primary-branch
Unfortunately users may need to use the branch switching to reinstall or use a webhook to force a branch switch. Otherwise they may not _see_ an update.
=> Add Primary Branch header for GitHub Updater

classes/PodsAPI.php
WordPress core does not do this kind of limitation on WP User queries and the column has seen total disuse over the years since WordPress has been developed. Plugins are using this column for their own purposes which causes unexpected conflicts with how Pods relationships and lists using `Pods::find()` queries for users.
Tested on client site and confirmed as working.
* Fixed: Stop limiting users being queried using the deprecated `user_status` column in the WP Users table to prevent conflicts from other plugin usage of the disused column. #5677
=> Do not limit users by user_status=0 anymore

classes/PodsData.php
Fixes #5803 
A DB prefix isn't required for WP and `strpos()` doesn't accept an empty string.
This also makes some minor code enhancements to PodsData.
=> Fix error if there is no prefix available

classes/Pods.php, includes/media.php, tests/phpunit/includes/tests-media.php
Fixes #4040 
PDF's tags like `{@id}` and `{@_src}` in each loops are converted to `{@image_attachment_url}` tags. This makes the PDF handled as an image.
I've chosen to fix this in the `field()` method instead of in frontier since a different solution would require an extra global tag like `pdf_attachment` or something which I didn't think was needed.
This makes sure if someone uses the `{@image_attachment_url}` tag the URL's get handled correctly.
Of course, if someone uses the `{@image_attachment}` tag this will always return an actual image (HTML).
This PR also removes duplicate code in `pods_image_url` for default value handling.
=> Fix PDF src in each loop.

classes/Pods.php, classes/fields/avatar.php, includes/media.php
Fixes #2738 
- Force the size of an avatar field if the parameter is provided (`{@avatar.32}`)
- Allow traversing through attachment object if the field name is registered as `avatar`. Supports the usage of `{@avatar._src}`
- Enhance support custom sizes in magic tags. Example: `{@image._src.300x750}` (creates new cropped image) and `{@image._src.60x60x0}` (creates new non-cropped image).
- Fixed: Avatar should always return a square image.
- Enhancement: Allow traversing in avatar attachment.
- Added: Support custom image sizes for all image field types in magic tags.
=> Force avatar size + enhance support for custom sizes

classes/Pods.php, readme.txt
Fixes #5845 
While The issue in 5845 is in fact incorrect usage of `pods()` this PR might be a nice enhancement in loading Pods objects.
=> Allow WP objects to be passed in `pods()`

components/Templates/Templates.php
Fixes #5875 
This PR adds 2 new options to Pods Templates:
- Boolean: Show no-access message (default: true)
- Wysiwyg: No access message (overwrites default)
=> Custom no access message for templates

includes/general.php
This allows Pods to not rely as much on `in_the_loop()` so the shortcode can be used in more flexible ways. This is needed for https://github.com/pods-framework/pods-beaver-builder-themer-add-on/pull/112
* Added: New filter `pods_shortcode_detect_from_current_post` allows you to override whether a shortcode should detect the post object outside of the loop (default is only when `in_the_loop()`).
=> Add pods_shortcode_detect_from_current_post filter for more flexibility

classes/Pods.php
Parse display filters for each value instead of the full array in case single is false.
If a Pod is extended and run through traversal the display filters are handled as single values while the actual value is an array since traversal always sets the `single` param to false.
@sc0ttkclark Maybe add an extra param for `display_filters` that sets the filter to run for multiple or a single instance?
Fixes #5985 
Related: https://wordpress.org/support/topic/error-with-post_title-in-xampp-host/
See issue.
=> Fix traversal display filters

includes/general.php
~~Optionally parse the `pagination` parameter as the pagination type.~~
Added `pagination_type` param.
Fixes #5977
=> Add pagination type to shortcode params

classes/PodsAPI.php
Simple switch to `pods_v`.
Fixes #5952
=> Use pods_v to prevent possible PHP notice

classes/PodsAPI.php, tests/phpunit/includes/Bugs/Test_5909.php
Fixes #5909 (Confirmed: 1x)
Fixes new bug introduces with #5665 
Tested with unit tests and #5909 fix.
Needs more unit tests.
This PR sets the fix in #5665 to only occur with WP object fields, not Pod options and other data.
=> Fix meta sanitizing (again)

classes/PodsAdmin.php, classes/PodsInit.php, components/I18n/I18n.php
=> Add WP 5.7 `filter_by_item` and `filter_by_date` labels

classes/PodsData.php, includes/general.php, ui/front/filters.php
Support taxonomies as filters in Pods::find()
Fixes #5994 
- Create some posts with various categories
- Add the following shortcode anywhere: `[pods name="post" filters="category" field="title"]`
- It should add a selectbox with all available categories
- Select a category and only the posts related to that category should show.
=> Support taxonomy filters in Pods::find() and other object fields

includes/media.php
Allow ID to be passed as param for `pods_audio` and `pods_video`
Will also enable the following magic tag usage:
```
[each videos]
{@ID,pods_video}
[/each]
```
Fixes #5983
=> Allow ID as parameter for audio and video

ui/js/dfv/pods-dfv.min.asset.json, ui/js/dfv/src/fields/datetime/datetime.scss, ui/js/dfv/src/fields/datetime/index.js
Fixes issue with DatePicker fields being cut off. 
#5965
1. Add a Datepicker field to the end of a group. 
2. Test that it is no longer cut off, and the group expands to fit it. 
- Fixes issue where date pickers were cut off.
=> Fix issue with datepicker being cut off

ui/js/dfv/pods-dfv.min.asset.json, ui/js/dfv/src/store/reducer.js
Fixes issue where fields disappear after a group is renamed.
#5980
1. Rename a group with fields.
2. The fields will still be shown after the name change.
- Fixes issue where fields disappear after a group is renamed.
=> Fix issue where fields disappear after a group is renamed

ui/js/dfv/pods-dfv.min.asset.json, ui/js/dfv/src/components/help-tooltip.scss, ui/js/dfv/src/config/prop-types.js, ui/js/dfv/src/fields/boolean-group/boolean-group-subfield.js, ui/js/dfv/src/fields/boolean-group/index.js
Fixes a few issues with Boolean Group fields.
1. Open an "Edit Field" modal, try the Boolean Group in the Kitchen Sink.
- Fix: Fixes issue with boolean group checkboxes needing to be clicked twice in the "Edit Field" modals.
- Fix: Fixes tooltip links not displaying inside Boolean Groups.
=> Fixes for Boolean Groups

classes/fields/avatar.php
=> Check if get_current_screen() exists in Avatar field

classes/PodsMeta.php
Fix warnings on admin when editing a user with a custom pod for non-existent $post variable, do_action would also not pass the right object over to hooks.
1. Create a user pod, add some fields to it.
2. Go to edit the user.
=> Fix meta_user do_action not using the right object.

classes/PodsUI.php
Export function first converted $params to an object, then get_params only merged $params if it was an array causing $params->full to always be false.
Fixes #3035
1. Go to any pot that supports exports and has more than 25 fields
2. Export
=> Fix Export to CSV Additional Action limit issues

Gruntfile.js, docs/release-workflow.md
Add --ver argument support to npm run version_update or grunt version_update, like: `npm run version_number -- --ver=1.2.3-a-1` would update all versions in their respective files to 1.2.3-a-1, the old style of updating package.json first and running without parameters still works.
1. Run `npm run version_number -- --ver=1.2.3-a-1`
2. Modify package json and run `npm run version_number`
=> Feature/add --ver argument support to grunt / npm run

classes/PodsUI.php
Update the way $options->fields is modified by first making a local copy then replacing the one in the object with the modified local variable.
The old method would only update the local copy of fields['manage'] and the object reference would remain untouched with an empty manage key.
#6048
=> PHP Notice "Indirect modification of overloaded property PodsArray::$fields has no effect" on Custom Settings Page

classes/fields/text.php
Resolve `Warning: strlen() expects parameter 1 to be string, array given in wp-content/plugins/pods/classes/fields/text.php on line 168`
None.
I was getting this error output. Casting the value to `(string)` resolves the Warning and still serves the purpose of the function.
None.
* Fix a PHP error output.
=> Resolve `strlen()` warning

classes/PodsMeta.php, components/I18n/I18n.php
Also modify group labels with the i18n component.
@sc0ttkclark Please check filter name. There are now some PodsForm, PodsAdmin and PodsMeta filters.
Fixes: #6148
- ~My code includes automated tests for PHP and/or JS (if applicable).~
=> Pods 2.8: Enhance getting Pod WhatsIt translations

classes/PodsData.php
Ensure last_table_info is an object and not boolean
[This commit](https://github.com/pods-framework/pods/commit/6efb7139fbf3cec383538397eb0104dc755d8c00) broke some traversals.  Must not be all of them or more people would have noticed.  My setup I was testing against had a 'custom-simple' relationship field.
=> Ensure last_table_info is an object and not boolean

classes/PodsRESTFields.php
This PR will enable field by field settings for read/write if all fields aren't enabled in the Pod.
Fixes #6287 (confirmed)
=> Bugfix: REST API field settings

src/Pods/Integrations/Polylang.php, src/Pods/Integrations/WPML.php
Fix getting relationship options for non-translatable objects.
Fixed: #6285
=> Bugfix i18n integration

components/I18n/I18n.php, src/Pods/Whatsit.php
This PR adds a filter to modify all Pod Whatsit args.
The i18n component uses this filter to modify other existing args where needed.
Fixes #6265 (confirmed)
Pods i18n component v1.1
=> i18n component v1.1 - translate Whatsit args

classes/fields/pick.php, ui/js/dfv/src/config/prop-types.js, ui/js/dfv/src/fields/pick/index.js
This PR will add an option to customize the "Add New" label for a pick field.
Note: the placeholder options do not work because of this issue: #6275
Fixes #6277
=> Customize Pick field label "Add New"

classes/fields/color.php, ui/js/dfv/src/config/prop-types.js, ui/js/dfv/src/fields/color/index.js
This PR will add two options to customize the color field labels.
Note: the placeholder options do not work because of this issue: #6275 
Fixes #6274
=> Customize Color field labels

classes/PodsI18n.php
The changes in 2.8.6 created a loop in getting the current language when using Polylang and having the User object extended.
This is because the Polylang integration uses `get_user_meta` which in turn calls get_current_language again.
Fixes #6334
=> Fix i18n loop since 2.8.6

ui/admin/setup-add.php
=> Wrong usage of is_type_covered(), should do the opposite

src/Pods/Blocks/Types/Field.php, src/Pods/Blocks/Types/Form.php, src/Pods/Blocks/Types/Item_List.php, src/Pods/Blocks/Types/Item_Single.php, src/Pods/Blocks/Types/View.php
=> Use `pods_trim` instead of `trim` to accept other var types

src/Pods/Theme/WP_Query_Integration.php
When accessing a 404 term archive Pods generates a warning.
Fixes #6383
=> Fix warning on 404 term pages

classes/PodsInit.php
`esc_html()` replaces single quotes with the html entity.
This now also happens for the post type labels.
This PR aims to fix this.
Fixes #6394
=> Undo single quote replace by esc_html

classes/PodsData.php
The change here https://github.com/pods-framework/pods/commit/55d150b631d153a29ae6fa8afca55226dd2727bc broke query generation on pick fields that don't have an explicit reference.  
For years now I've had code that called
```
$where = array( array( 'key' => 'style_revision', 'value' => '2015' ) );
$params = array( 'where' => $where, 'limit' => 16 );
$pod->find($params);
```
This stopped working with 2.8.  I can fix it in my code by changing the key to `style_revision.post_title` which might have always been the proper way to do it but we should retain backwards compatibility.
=> Retain backwards compatibility with field name passed for pick fields

src/Pods/Integrations/WPML.php
Fixes #6448 
- Compatibility: Refresh language cache after WPML switched language.
=> Refresh language cache after WPML has switch language.

components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php
The object param used to check for a Pod was incorrect.
This PR returns the option to use auto templates for term archives (description or other custom hook)
Fixes #6368
1. Create taxonomy
2. Make sure your theme used a hook for taxonomy archives (archive.php). Default: `the_archive_description()`
3. Add auto template
4. Should be visible!
=> Fix term autotemplates

ui/js/jquery.pods.js
Fix for multi-select fields having values imploded when saved on Pods ajax forms.
Fixes https://github.com/pods-framework/pods/issues/6216
Use package from https://github.com/pods-framework/pods/issues/6216#issuecomment-1076280688, and try replicating the issue. 
Fix: Fix for multi-select fields having values imploded when saved on Pods ajax forms.
=> Fix for multi-select fields having values imploded when saved on older ajax forms

classes/PodsAPI.php, includes/general.php, src/Pods/Whatsit/Field.php
This work ensures better support for table-based relationships and any other plugins that want to filter the final data before the saving processes for relationships/data/meta.
=> Pre-process relationships during save_pod_item() so that is done before saving to table storage as well

classes/PodsForm.php, classes/PodsMeta.php
When having multiple field groups for the media pod it results in an init loop rendering duplicate fields.
Fixes #6564
=> Fix media modal fields init loop

classes/PodsField.php, includes/data.php, src/Pods/Admin/Config/Field.php
Currently the repeatable fields use the `pods_serial_comma` function using the default parameters.
This PR aims to extend the repeatable options the same way as the Pick field by adding a format field and a custom separator if the format field is set to `custom`.
Fixes #6890
=> Custom repeatable fields separators

components/Templates/Templates.php
Since Pods 2.9.5 (commit f433559a602f1ced90f57dc14f2766ccf9567fc8) the Pods template was missing the requires assets.
This PR fixed that.
Fixes #6921
=> Fix template edit page editor

classes/PodsMeta.php
when i try to register taxonomy fields via the code using the example from pods.io site, it leads to a fatal error. You can replicate the error with the below code snippet
```
add_action('init', function () {
$pod = [
'name'           => 'category',
'label'          => 'Authors',
'description'    => '',
'type'           => 'taxonomy',
'storage'        => 'meta',
'label_singular' => 'Author',
'public'         => '1',
];
pods_register_type( $pod['type'], $pod['name'], $pod );
$group = [
'name'        => 'more_fields',
'label'       => 'More Fields',
'description' => '',
'weight'      => 0,
];
$group_fields = [
'books' => [
'name'              => 'books',
'label'             => 'Books',
'description'       => '',
'weight'            => 0,
'type'              => 'pick',
'pick_object'       => …
```
=> Fix error in registering taxonomy fields via code

classes/PodsMeta.php
Fixes the `cpac_meta_value()` function to always return a string, as the ACP `format()` function expects a string for its first argument.
Fixes #6965.
1. Define a new multi-select field for a post type. Leave it uninitialized.
2. Display the new field as column on the post type admin list view.
3. You should not see an internal error message in one of the columns, nor a fatal TypeError in debug.log.
* Makes `cpac_meta_value()` always return a string, as the ACP `format()` function expects a string for its first argument.
=> Make `cpac_meta_value()` always return a string

components/I18n/I18n.php
=> Fix occasional php warning

classes/Pods.php
Set empty string as default
Fixes #7075
=> Fix PHP Deprecated: strlen(): Passing null

classes/Pods.php
When passing a WP object to `pods()` we can use it's ID instead of the queried object.
This use of the param makes way more sense.
Fixes #7094
=> Fetch object ID from WP object

classes/fields/pick.php, includes/data.php, src/Pods/Admin/Config/Field.php, tests/codeception/wpunit/Pods/Field/PodsField_PickTest.php
This PR adds 3 extra display formats for field config:
- Line Breaks
- Unordered List
- Ordered List
Fixes #7044
=> Add extra repeatable formats

src/Pods/Integrations/Polylang.php
This PR will update our compatibility code with the latest Polylang changes
Fixes #7139
=> Use new get_tax_prop method with backwards compatibility

classes/PodsUI.php, components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php, components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Settings.php
Changed the prio to an int,
Fixes #7145
=> Fix deprecated PHP

components/Templates/Templates.php, ui/styles/src/base/_wizard.scss, ui/styles/src/libs/_jquery-qtip.scss
Add `color: inherit;` to `h3` and `a` of `.qtip-content` div, now heading and anchor link has good color contract ratio.
Fixes #7118 
1. Go to 'Pods Admin'
2. Click on 'Add New'
3. Click on 'Create New'
4. Hover 'Content Type' `?` icon
=> fix: form ui label tooltip heading and anchor color contract (#7118)

components/Templates/includes/functions-pod_reference.php
https://wordpress.org/support/topic/template-image-url-for-full-size/
Fixes #7183
=> Include full image size in reference list

classes/fields/pick.php
Enhance compatibility with other plugins.
Fixes #7181
=> Use prefix instead of parsing our own

.editorconfig
Currently TAB characters are displayed as 8 spaces.
This PR make tabs half as wide.
=> Make GitHub display shorter tabs

classes/PodsInit.php
Currently if you leave the custom capability field empty it will fallback to `post` instead of the CPT name.
This PR fixes this :)
Related #7218
1. Create CPT with custom cap
3. Leave custom cap empty
4. Switch to role that includes the custom edit caps (edit_cpt/edit_cpts) but doesn't have the default edit_post and edit_posts caps.
5. Try to edit CPT post
6. You can't! :(
7. Apply patch
8. You can! :)
=> Fix custom capability fallback

ui/js/blocks/src/blocks/components/RenderedField.js
Adds label to ColorPicker `color` field in Pods Block API.
Attempted to do same for MediaUpload, but `file` field does not render at all when I try with the example code below.
#7305 
Run `npm run build-dev` or similar.
Add the block below.
Color Picker should have a label.
File field does not render at all when I attempt it -- nothing has been changed there yet.
Descriptions may need to be added as well.
```php
<?php
/**
* Plugin Name: My Custom Pods Block
* Plugin URI: https://docs.pods.io/code/blocks-api/
* Description: Custom block built using the Pods Block PHP API. No Javascript needed!
* Author Name: Scott Kingsley Clark
* Author URI: https://skc.dev/
*/
/**
* Want a quick overview and live demo? Check out the screencast here: https://docs.pods.io/code/blocks-api/
*/
/**
* Example …
```
=> Wrap ColorPicker in BaseControl for label.

classes/fields/pick.php
- Change taxonomy sync option from text to boolean.
- Change bidirectional relationship check from preventing taxonomy sync feature from running due to early `return`
#7334
Bug: Relationship Field Taxonomy Sync now works correctly and presents as checkbox. User Interface for taxonomies using this feature should be hidden in taxonomy Admin UI settings to avoid confusion, as changes relationship field will update core taxonomy, but core taxonomy user interfaces will not update relationship field. @pdclark
=> Relationship Field Sync Taxonomy: Checkbox & Unblock Sync

classes/PodsAdmin.php, classes/PodsRESTFields.php
De default value for the `write_all` option of a Pod was set to the Pod name. This results in incorrect parsing of a boolean in `PodsRESTFields::field_allowed_to_extend()` in `write` mode.
@sc0ttkclark See testing instructions. I'm not sure how you would like to implement something that will repair old Pods. You could check for `! empty()` instead of using `filter_var()` but that might not be desirable. 
Fixes #7327
1. Create a Pod without this patch and enable write mode.
2. Go to `PodsRESTFields::field_allowed_to_extend()` and dump `$all_fields_can_use_mode`. It will return false, allways.
3. Verify with `$pod->get_arg( $pod_mode_arg, 'value_not_set' )` and see it returns the Pod name instead of a 1 or 0.
4. Apply this patch
5. Disable REST write access and save Pod (important, …
=> REST API Write access - Fix invalid default value

classes/PodsRESTFields.php, tests/codeception/wpunit/Pods/PodsRESTFieldsTest.php
Instead of checking if the user is logged in it also checks if the user a basic auth for applications is used.
Fixes #7340
@sc0ttkclark I'm not 100% sure this will be the best method. You could also already set the current WP user so WP core doesn't revalidate using the same method. I'll leave this up to your judgement.
See #7340
Try the same with this patch and see it now works!
=> Improve REST authentication method when registering fields

classes/Pods.php
Fixes #7376 
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See '....'
=> Validate non empty value

classes/PodsUI.php
Fix the message "PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/wp-content/plugins/pods/classes/PodsUI.php on line 3003" that show on pods manage page
1. Create a new Pod
2. Sett it to show on menu
3. Enter to de menu
=> Fixing strlen() error

.github/workflows/wordpress-plugin-deploy.yml
This uses [the WordPress Plugin Attestation action](https://github.com/johnbillion/action-wordpress-plugin-attestation) to generate a build provenance attestation for the zip file of Pods. This ties the zip file on wordpress.org back to the GitHub Actions workflow that performed the deployment.
This isn't testable in isolation because the workflow only runs when you publish a release, but [it's used by several other plugins](https://github.com/johnbillion/action-wordpress-plugin-attestation/network/dependents).
Enhancement: A build provenance attestation is now generated for each deployment to the wordpress.org plugin directory. (@johnbillion)
=> Generate build provenance attestation during deployment

classes/PodsUI.php
Fixed Function in PodsUI.php
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See '....'
=> Fixed Function in PodsUI.php
